uberfire-parent-with-dependencies/pom.xml

I guess comment just needs updating. If its correct, please just close and ignore this pull request.

Fixed module name in comment

---

uberfire-parent-with-dependencies/pom.xml

See also: 
- https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/169
- https://github.com/uberfire/uberfire/pull/337
- https://github.com/uberfire/uberfire-extensions/pull/258
- https://github.com/droolsjbpm/kie-wb-common/pull/337
- https://github.com/droolsjbpm/jbpm-designer/pull/220
- https://github.com/droolsjbpm/jbpm-form-modeler/pull/46
- https://github.com/droolsjbpm/jbpm-console-ng/pull/395
- https://github.com/droolsjbpm/drools-wb/pull/156
- https://github.com/droolsjbpm/kie-wb-distributions/pull/261

UF-295 - Updrading lucene to 5.3.1

---

uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/JAASAuthenticationService.java
uberfire-nio2-backport/uberfire-nio2-api/src/main/java/org/uberfire/java/nio/file/Files.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-fs/src/main/java/org/uberfire/java/nio/fs/file/BaseSimpleFileSystem.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-fs/src/main/java/org/uberfire/java/nio/fs/file/SimpleFileSystemProvider.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystem.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/IOException.java
uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/file/ClosedWatchServiceException.java

See also:
https://github.com/droolsjbpm/drools-wb/pull/162
https://github.com/droolsjbpm/kie-uberfire-extensions/pull/26

fix some exceptions and exception messages (mostly adding messages)

---

pom.xml
uberfire-parent-with-dependencies/pom.xml

This replaces https://github.com/uberfire/uberfire/pull/359.

Upgrade ip-bom from 7.0.0.CR1 to 7.0.0.CR2 + related fixes

---

uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/menu/MenuBuilder.java

* the import was wrong, all other classes are using
also javax.inject.Inject

Use javax.inject.Inject instead of com.google.inject.Inject

---

uberfire-parent-with-dependencies/pom.xml

This reverts commit 888083b46dfa4b17f185db56959bb36c4cc484e4.

Revert "[BZ-1322171] upgrade XStream from 1.4.7 to 1.4.9"

---

uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-backend/src/test/java/org/uberfire/ext/editor/commons/backend/validation/ValidationUtilsTest.java

(part X of moving-tests-to-community series)

add test for ValidationUtils

---

uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/history/VersionMenuDropDownButton.java
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/history/VersionMenuDropDownButtonView.java
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/history/VersionRecordManager.java
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/history/VersionMenuDropDownButtonTest.java
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/history/VersionRecordManagerTest.java

See https://issues.jboss.org/browse/GUVNOR-2539

GUVNOR-2539: Guided Decision Table Editor: VersionRecordManager does not refresh when different documents are selected

---

pom.xml
uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-showcase/__rootArtifactId__-webapp/pom.xml
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-webapp/pom.xml
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-wildfly/pom.xml
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-wildfly/src/main/java/org/uberfire/ext/security/management/wildfly/properties/WildflyGroupPropertiesManager.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-wildfly/src/main/java/org/uberfire/ext/security/management/wildfly/properties/WildflyUserPropertiesManager.java
uberfire-extensions/uberfire-wires/uberfire-wires-webapp/pom.xml
uberfire-showcase/uberfire-webapp/pom.xml

* refactored the wildfly version property
into uf-parent for better reusability

Upgrade wildfly-dist to 10.0.0.Final.

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetMouseDoubleClickHandler.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/pinning/impl/DefaultPinnedModeManager.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/layer/pinning/impl/DefaultPinnedModeManagerTest.java

See https://issues.jboss.org/browse/GUVNOR-2553

GUVNOR-2553: Guided Decision Table Editor: Fix exit 'pinned mode' when closing a document

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/context/GridBodyColumnRenderContext.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/context/GridHeaderColumnRenderContext.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseMoveHandler.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidget.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/GridColumnRenderer.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/BaseGridColumnRenderer.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/ColumnRenderingStrategyFlattened.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/ColumnRenderingStrategyMerged.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/GridRenderer.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRenderer.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/GridRendererTheme.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/BlueTheme.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/GreenTheme.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/MultiColouredTheme.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/RedTheme.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/pinning/impl/DefaultPinnedModeManager.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/layer/pinning/impl/DefaultPinnedModeManagerTest.java

See https://issues.jboss.org/browse/GUVNOR-2559

GUVNOR-2559: Guided Decision Table Editor: Improve appearance (for Red Hat Summit)

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/DefaultGridLayer.java

See https://issues.jboss.org/browse/GUVNOR-2562

GUVNOR-2562: Guided Decision Table Editor: Clicking on GridLayer when editing cell does not update View

---

pom.xml
uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-parent-with-dependencies/pom.xml
uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-showcase/__rootArtifactId__-distribution-wars/pom.xml
uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-showcase/__rootArtifactId__-distribution-wars/src/main/assembly/assembly-showcase-tomcat-7_0.xml
uberfire-backend/uberfire-backend-cdi/pom.xml
uberfire-backend/uberfire-backend-server/pom.xml
uberfire-bom/pom.xml
uberfire-commons/pom.xml
uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/pom.xml
uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-backend/pom.xml
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/pom.xml
uberfire-extensions/uberfire-security/uberfire-servlet-security/pom.xml
uberfire-io/pom.xml
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/pom.xml
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/CustomDiffCommand.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/JGitUtil.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProviderHookTest.java
uberfire-security/uberfire-security-api/pom.xml
uberfire-server/pom.xml
uberfire-server/src/main/java/org/uberfire/server/locale/GWTLocaleHeaderFilter.java
uberfire-server/src/test/java/org/uberfire/server/FileUploadServletTest.java
uberfire-server/src/test/java/org/uberfire/server/locale/GWTLocaleHeaderFilterTest.java
uberfire-showcase/showcase-distribution-wars/pom.xml
uberfire-showcase/showcase-distribution-wars/src/main/assembly/assembly-showcase-tomcat-7_0.xml

* fixes after JGit 3.x -> 4.x ugprade
* minor updates related to JEE Spec upgrades
Depends on https://github.com/errai/errai/pull/180.

Upgrade IP BOM to 7.0.0.CR4 + related fixes

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/GridData.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridData.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/context/GridBodyColumnRenderContext.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDHandlersState.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseDownHandler.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseMoveHandler.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseUpHandler.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidget.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetMouseClickHandler.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetMouseDoubleClickHandler.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/GridWidgetConnector.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/GridColumnRenderer.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/BaseGridColumnRenderer.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/ColumnRenderingStrategyFlattened.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/ColumnRenderingStrategyMerged.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/GridRenderer.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRenderer.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRendererHelper.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/GridRendererTheme.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/BlueTheme.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/GreenTheme.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/MultiColouredTheme.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/RedTheme.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/GridLayer.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/DefaultGridLayer.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseDownHandlerTest.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseMoveHandlerTest.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseUpHandlerTest.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetMouseClickHandlerTest.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetMouseDoubleClickHandlerTest.java

See https://issues.jboss.org/browse/GUVNOR-2544

GUVNOR-2544: Guided Decision Table Editor: Layout manager for tables.

---

uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/WebAppListener.java
uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/WebAppSettings.java
uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/authz/AuthorizationPolicyDeployer.java
uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/RoleLoader.java
uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/WebAppSettingsTest.java
uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/authz/AuthzPolicyDeployerTest.java
uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/security/RoleLoaderTest.java

Fix + tests
@csadilek Can you verify please? Specially the usage of a ServletContextListener to capture the webapp init/detroy events.

UF-321: Error reading roles from web.xml and loading security policy files

---

uberfire-docs/.gitignore
uberfire-docs/docs/security/annotations.md
uberfire-docs/docs/security/authzPolicyStorage.md
uberfire-docs/docs/security/security.md
uberfire-docs/docs/security/workbenchAssets.md

Related to https://github.com/uberfire/uberfire-docs/pull/18
@dgutierr could you please take a look on this?

UF-280: Security doc fine tuning (moving PR from UF-docs)

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-scratchpad/src/main/java/org/uberfire/ext/wires/core/scratchpad/client/perspectives/WiresScratchPadPerspective.java
uberfire-extensions/uberfire-wires/uberfire-wires-webapp/src/main/java/org/uberfire/ext/wires/client/ShowcaseEntryPoint.java

Quick fix: create a default perspective on wires in order to prevent security alert

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/demo/WiresGridsDemoPresenter.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/GridColumnRenderer.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/BaseGridColumnRenderer.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/ColumnRenderingStrategyFlattened.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/columns/impl/ColumnRenderingStrategyMerged.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRenderer.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRendererHelper.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/GroupingToggle.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/BlueTheme.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/GreenTheme.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/MultiColouredTheme.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/themes/impl/RedTheme.java

- Changed collapse/expand toggle.
- Fixed some Wires Showcase rendering issues.
- Renamed a getter to be more consistent with what it returns.

GUVNOR-2559: Guided Decision Table Editor: Improve appearance (for Red Hat Summit) - Changed collapse/expand toggle; and fixed some Show Case issues

---

uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/HelpIcon.java

Using setHelpTitle/setHelpContent currently has no effect as the popover instance is not updated.

UF-328: HelpIcon - allow title/content update

---

uberfire-client-api/src/main/java/org/uberfire/client/mvp/UpdatedLockStatusEvent.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/LockManagerImpl.java

cherry-pick to 0.8.x for Designer bug https://issues.jboss.org/browse/RHBPMS-4021

UF-308: UpdatedLockStatusEvent: Include Path parameter. (#375)

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseMoveHandler.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/GridWidget.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseMoveHandlerTest.java

See https://issues.jboss.org/browse/GUVNOR-2591
Video of issue [here](http://screencast.com/t/Q0AR0ms7WD4P).

GUVNOR-2591: Guided Decision Table Editor: Dragging a 'table title' pans the Canvas. It should drag the grid.

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/DefaultGridLayer.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/pinning/impl/DefaultPinnedModeManager.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/layer/pinning/impl/DefaultPinnedModeManagerTest.java

See https://issues.jboss.org/browse/GUVNOR-2597

GUVNOR-2597: Guided Decision Table Editor: Exiting 'pinned mode' doesn't restore correct TransformMediator

---

uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/WebAppSettings.java
uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/authz/AuthorizationPolicyDeployer.java
uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/RoleLoader.java
uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/WebAppSettingsTest.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/resources/i18n/UsersManagementWidgetsConstants.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/MultiplePermissionNodeEditorView.css
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/group/workflow/GroupEditorWorkflow.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/role/workflow/BaseRoleEditorWorkflow.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/role/workflow/RoleEditorWorkflow.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/resources/org/uberfire/ext/security/management/client/resources/i18n/UsersManagementWidgetsConstants.properties
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/group/workflow/GroupEditorWorkflowTest.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/role/workflow/RoleEditorWorkflowTest.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/dropdown/LiveSearchDropDown.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/dropdown/LiveSearchDropDownView.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/dropdown/PerspectiveDropDown.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/dropdown/LiveSearchDropDownTest.java
uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/authz/PermissionCollection.java
uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DefaultPermissionCollection.java
uberfire-security/uberfire-security-api/src/test/java/org/uberfire/security/impl/authz/AuthorizationManagerTest.java
uberfire-security/uberfire-security-api/src/test/java/org/uberfire/security/impl/authz/PermissionCollectionTest.java
uberfire-security/uberfire-security-api/src/test/java/org/uberfire/security/impl/authz/PermissionManagerTest.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/authz/PerspectiveAction.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/authz/PerspectivePermissionTest.java

Fixes+tests for some of the issues reported recently by QE
@romartin Can you review and ack please?

Security management related fixes

---

uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/ACLSettingsView.html
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/BasePermissionNodeEditor.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/LeafPermissionNodeEditor.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/LeafPermissionNodeEditorView.html
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/LeafPermissionNodeEditorView.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/MultiplePermissionNodeEditor.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/MultiplePermissionNodeEditorView.html
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/MultiplePermissionNodeEditorView.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/PermissionExceptionSwitch.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/PermissionExceptionSwitchView.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/PermissionSwitch.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/PermissionSwitchToogle.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/PermissionSwitchView.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/LeafPermissionNodeEditorTest.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/MultiplePermissionNodeEditorTest.java
uberfire-security/uberfire-security-client/src/main/java/org/uberfire/security/client/authz/tree/PermissionNode.java
uberfire-security/uberfire-security-client/src/main/java/org/uberfire/security/client/authz/tree/impl/AbstractPermissionNode.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/authz/PerspectiveTreeProvider.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/resources/i18n/PermissionTreeI18NImpl.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/resources/i18n/PermissionTreeI18n.java
uberfire-workbench/uberfire-workbench-client/src/main/resources/org/uberfire/client/resources/i18n/PermissionTreeConstants.properties

UF-325: Add help icons with tips to workbench permissions
UF-329: Add automatic disabling of illogical combinations in Security perspective
@ederign Can you please verify?

Security management enhancements

---

uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/common/ConcurrentChangePopup.java

See https://issues.jboss.org/browse/BPMSPL-301

BPMSPL-301: request to improve error message while uploading spreadsheet with multibyte name

---

pom.xml
uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-showcase/__rootArtifactId__-webapp/src/main/resources/__capitalizedRootArtifactId__Showcase.gwt.xml
uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-showcase/__rootArtifactId__-webapp/src/main/webapp/index.html
uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-showcase/__rootArtifactId__-webapp/src/main/webapp/login.jsp
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-webapp/src/main/resources/org/uberfire/ext/security/management/UberfireSecurityManagementShowcase.gwt.xml
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-webapp/src/main/webapp/security-management.html
uberfire-extensions/uberfire-wires/uberfire-wires-webapp/src/main/resources/org/uberfire/ext/wires/WiresShowcase.gwt.xml
uberfire-extensions/uberfire-wires/uberfire-wires-webapp/src/main/webapp/wires.html
uberfire-showcase/uberfire-webapp/src/main/java/org/uberfire/client/ShowcaseEntryPoint.java
uberfire-showcase/uberfire-webapp/src/main/resources/org/uberfire/UberfireShowcase.gwt.xml
uberfire-showcase/uberfire-webapp/src/main/webapp/login.jsp
uberfire-workbench/uberfire-workbench-client-views-patternfly/pom.xml
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/menu/WorkbenchMenuBarView.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/resources/org/uberfire/client/views/PatternFly.gwt.xml
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/resources/org/uberfire/client/views/PatternFlyTheme.gwt.xml
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/resources/org/uberfire/client/views/static/uberfire-patternfly.css

Style fixes for upgrade
New theme GWT module

UF-305 - PatternFly upgrade to version 3.6.0

---

uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/authz/AuthorizationPolicyDeployer.java
uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/authz/AuthorizationPolicyMarshaller.java
uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/authz/AuthzPolicyMarshallerTest.java
uberfire-backend/uberfire-backend-server/src/test/resources/WEB-INF/classes/security-policy.properties
uberfire-backend/uberfire-backend-server/src/test/resources/WEB-INF/classes/split/security-policy.properties
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-webapp/src/main/resources/security-policy.properties
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/BasePermissionNodeEditor.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/LeafPermissionNodeEditor.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/LeafPermissionNodeEditorView.css
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/MultiplePermissionNodeEditor.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/PermissionExceptionSwitch.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/PermissionExceptionSwitchView.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/PermissionSwitch.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/PermissionSwitchToogle.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/MultiplePermissionNodeEditorTest.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/PermissionExceptionSwitchTest.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/PermissionSwitchTest.java
uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/authz/AuthorizationPolicy.java
uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/AuthorizationPolicyBuilder.java
uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DefaultAuthorizationEntry.java
uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DefaultAuthorizationPolicy.java
uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DefaultPermissionCollection.java
uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DefaultPermissionManager.java
uberfire-security/uberfire-security-api/src/test/java/org/uberfire/security/impl/authz/AuthorizationManagerTest.java
uberfire-security/uberfire-security-api/src/test/java/org/uberfire/security/impl/authz/HomePerspectiveTest.java
uberfire-security/uberfire-security-api/src/test/java/org/uberfire/security/impl/authz/PermissionCollectionTest.java
uberfire-showcase/uberfire-webapp/src/main/resources/security-policy.properties

UF-329: Add automatic disabling of illogical combinations in Security perspective
UF-343: User without assigned role has all the permissions allowed
UF-360: No gap between permission name and help icon
Fix + tests
@ederign Can you review please?

Security management fixes

---

uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/CopyPopUpViewProducer.java
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/DefaultView.java
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/popups/CopyPopUpView.java
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/popups/DeletePopUpView.html
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/popups/RestorePopUpView.html
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/popups/SavePopUpView.html
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/popups/commons/ToggleCommentView.html

Creates a new qualifier `@DefaultView` that solves the CDI ambiguity.

Fix the CopyPopUpView injection

---

uberfire-showcase/uberfire-webapp/src/main/resources/security-policy.properties

@csadilek pointed out that uberfire showcase is not working after https://github.com/uberfire/uberfire/commit/a4ab262b24eaef0e7899af411afd2836085b93c3 . 
This PR is to put https://github.com/uberfire/uberfire/commit/a4ab262b24eaef0e7899af411afd2836085b93c3 solution in master.

Showcase bug fix: adding required roles for uberfire showcase.

---

uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/menu/BasicFileMenuBuilderImpl.java
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/menu/BasicFileMenuBuilderTest.java

Fix use of PathProvider.
(Plus change to lamda's)
@karreiro Would you mind reviewing please?

GUVNOR-2431: Redesign Copy, Save, Rename, Restore and Delete Popups

---

uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-client-wb/README.md
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-webapp/README.md

@ederign A README file I forgot to update during UF-280 development.

UF-280: Security management README tweaks

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/columns/BooleanDOMElementColumn.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/columns/BooleanDOMElementColumnTest.java

See https://issues.jboss.org/browse/GUVNOR-2622

GUVNOR-2622: [Guided Decision Table] 'Check Box' doesn't react to press of 'Enter'

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/SelectionExtension.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/SelectionExtensionTest.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/selections/impl/BaseCellSelectionManagerTest.java

See https://issues.jboss.org/browse/GUVNOR-2624

GUVNOR-2624: Guided Decision Table Editor: Selection range does not extend correctly with keyboard navigation

---

uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/history/VersionMenuItemLabel.ui.xml
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/resources/i18n/CommonConstants.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/resources/org/uberfire/ext/widgets/common/client/resources/i18n/CommonConstants.properties

https://issues.jboss.org/browse/RHBPMS-1725

RHBPMS-1725 : [ALL LANG] Unlocalized string 'Project Explorer' in Authoring -> Project Authoring.

---

uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-lucene/src/main/java/org/uberfire/ext/metadata/backend/lucene/LuceneConfigBuilder.java
uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-lucene/src/main/java/org/uberfire/ext/metadata/backend/lucene/index/CustomAnalyzerWrapperFactory.java

Change Impact, Part I: building a reference infrastructure that we can query.
For an explanation, see https://github.com/droolsjbpm/kie-wb-common/pull/414
PR set:
- https://github.com/uberfire/uberfire/pull/455
- https://github.com/droolsjbpm/kie-wb-common/pull/414
- https://github.com/droolsjbpm/drools-wb/pull/257
- https://github.com/droolsjbpm/jbpm-designer/pull/375
- https://github.com/droolsjbpm/jbpm-form-modeler/pull/63

GUVNOR-2173 - Asset Oracle: Change Impact prediction

---

pom.xml
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/pom.xml
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/JGitUtil.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/GitCommand.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/Squash.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/exceptions/ConcurrentRefUpdateException.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/exceptions/GitException.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/AbstractTestInfra.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProviderBytemanTest.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProviderTest.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitSquashingTest.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/resources/byteman/squash.btm
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/resources/byteman/squash_exception.btm
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/resources/byteman/squash_lock.btm
uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/options/SquashOption.java

Squash command added to JGit repository. Also added to the JGitFileSystemProvider in the setAttribute method.
GitCommand added to implement git commands based on _command pattern_.

Git Squash Command 

---

uberfire-api/src/main/java/org/uberfire/mvp/impl/ExternalPathPlaceRequest.java
uberfire-api/src/main/java/org/uberfire/mvp/impl/ForcedPlaceRequest.java
uberfire-api/src/main/java/org/uberfire/mvp/impl/PathPlaceRequest.java
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-api/src/main/java/org/uberfire/ext/editor/commons/readonly/ReadOnlyPathPlaceRequest.java
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/history/VersionHistoryScreenPlace.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/PanelManagerImpl.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/PanelManagerTest.java

- Add test to ensure onSelectPlaceEvent sets focus on correct presenter

Add missing toString methods to PlaceRequest sub types

---

uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/pom.xml
uberfire-docs/docs/gettingStarted/5minIntroduction.md

It is not possible to build demo project from official ubefire site if you going thought tutorial steps. There are possible fixes for this.

Tutorial fixes

---

uberfire-backend/uberfire-backend-server/pom.xml
uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/io/object/ObjectStorage.java
uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/io/object/ObjectStorageImpl.java
uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/io/object/ObjectStorageTest.java
uberfire-backend/uberfire-backend-server/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider
uberfire-extensions/uberfire-preferences/uberfire-preferences-backend/src/main/java/org/uberfire/ext/preferences/backend/PreferenceStorageImpl.java
uberfire-extensions/uberfire-preferences/uberfire-preferences-backend/src/test/java/org/uberfire/ext/preferences/backend/CustomObject.java
uberfire-extensions/uberfire-preferences/uberfire-preferences-backend/src/test/java/org/uberfire/ext/preferences/backend/PreferenceStorageImplTest.java
uberfire-extensions/uberfire-preferences/uberfire-preferences-backend/src/test/java/org/uberfire/ext/preferences/backend/PreferenceStoreImplTest.java
uberfire-extensions/uberfire-preferences/uberfire-preferences-backend/src/test/resources/ErraiApp.properties

This is an abstraction of a Git Storage, it is based on @paulovmr PreferenceStorage.
@ederign 
@porcelli

ObjectStorage implementation

---

uberfire-docs/docs/gettingStarted/5minIntroduction.md
uberfire-docs/docs/gettingStarted/improvingYourFirstApp.md
uberfire-showcase/uberfire-webapp/src/main/webapp/plugins/home.splash.html

Missing whitespace in archetype fix
Duplicate "the"
Welcome pictures path fix for demo-showcase

Some fixes for tutorial and demo-showcase

---

uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProviderBytemanTest.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/resources/byteman/squash.btm

@ederign It was not running in parallel, but it was getting stuck because of the repeatead rendezvous name. I've changed it and now is working properly

Byteman test locking solved

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/demo/WiresGridsDemoPresenter.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/demo/WiresGridsDemoView.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/demo/WiresGridsDemoViewImpl.html
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/demo/WiresGridsDemoViewImpl.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/demo/resources/i18n/WiresGridsDemoConstants.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidget.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/GridLienzoPanel.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/resources/org/uberfire/ext/wires/core/grids/client/demo/resources/i18n/WiresGridsDemoConstants.properties
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetRenderingTest.java

See https://issues.jboss.org/browse/GUVNOR-2655

GUVNOR-2655: Guided Decision Table: Checkbox remains in row after last row is deleted

---

pom.xml
uberfire-parent-with-dependencies/pom.xml

upgraded to jboss-ip-bom 6.0.8.Final

---

uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/JGitUtil.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/ThrowableSupplier.java

`cherry-pick` from master. I supressed the tests here due the need of new dependencies to run it (byteman, etc...) that I'm not sure if it's worth to add here.
Master PR: #499

UF-401: improve random windows fails.

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/demo/WiresGridsDemoPresenter.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/demo/WiresGridsDemoView.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/demo/WiresGridsDemoViewImpl.html
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/demo/WiresGridsDemoViewImpl.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dom/single/impl/BaseSingletonDOMElementFactory.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dom/single/impl/ListBoxSingletonDOMElementFactory.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dom/single/impl/TextBoxSingletonDOMElementFactory.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/edit/EditorPopup.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/GridLienzoPanel.java

See https://issues.jboss.org/browse/GUVNOR-2685

GUVNOR-2685: Guided Decision Table Editor: Keyboard navigation should not be attached to RootPanel

---

uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/Clone.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/Fork.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/commands/Mirror.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProviderMigrationTest.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProviderWithFoldersTest.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitForkTest.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitMirrorTest.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/resources/simplelogger.properties

The goal is to have the possibility to fork any git repository inside the niogit directory.
To complete the goal we need:
* Separate git repositories into different directories. Those directories are named like the Organizational Units.
* Create a Fork command that copy all the content of the repository to fork and add the reference to the internal path of the origin repository.
* Write information about fork so we can track where those forks are, how many forks has those repositories, etc.

[UF-403] Fork and Mirror

---

uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/pom.xml

This fixes archetype-resources/pom.xml which contains duplicate tag repositories.

[UF-414]: Fix duplicate tag repositories

---

uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/rows/EmptyDropRowView.java

use javax.inject.Inject instead of com.google.inject.Inject

Fix @Inject import

---

uberfire-server/src/main/java/org/uberfire/server/locale/GWTLocaleHeaderFilter.java
uberfire-server/src/test/java/org/uberfire/server/locale/GWTLocaleHeaderFilterTest.java
uberfire-server/src/test/resources/expected-2-sample.html
uberfire-server/src/test/resources/expected-4-sample.html

See https://issues.jboss.org/browse/RHBPMS-4129
This is the corollary of https://github.com/uberfire/uberfire/pull/551 for master.
(cherry picked from commit 3eefc14a3272e335d38f770fdf45ef510766dde5)

RHBPMS-4129: Unlocalized 'Please wait. Loading application...' spinner.

---

uberfire-api/src/main/java/org/uberfire/mvp/impl/ConditionalPlaceRequest.java
uberfire-api/src/main/java/org/uberfire/mvp/impl/DefaultPlaceRequest.java
uberfire-api/src/test/java/org/uberfire/mvp/impl/ConditionalPlaceRequestTest.java
uberfire-extensions/uberfire-wires/uberfire-wires-webapp/src/main/java/org/uberfire/ext/wires/client/ShowcaseEntryPoint.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceManagerImpl.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/panels/impl/PlaceManagerTest.java

Usage: new ConditionalPlaceRequest( "UFWidgets" ).when( predicate ).orElse( new DefaultPlaceRequest( "AppsPerspective" ) )
Use case: Open Authoring and if the repo/projects are empty, redirect to LibraryPerspective (without a weird blink).

Conditional Place Request

---

uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-backend/src/main/java/org/uberfire/ext/plugin/backend/PluginMediaServlet.java
uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-backend/src/test/java/org/uberfire/ext/plugin/backend/PluginMediaServletTest.java

See https://issues.jboss.org/browse/RHBRMS-2687
____
- Before:
- After:

RHBRMS-2687: [Screen Plugin] Fail to upload picture on WAS and IE11

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/demo/WiresGridsDemoPresenter.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/demo/resources/i18n/WiresGridsDemoConstants.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRenderer.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/resources/org/uberfire/ext/wires/core/grids/client/demo/resources/i18n/WiresGridsDemoConstants.properties
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRendererTest.java

See https://issues.jboss.org/browse/GUVNOR-2750

GUVNOR-2750: Guided Decision Table Editor: Multi-line Selected Cell highlight is not clipped vertically with Header

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/DefaultGridLayer.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/DefaultGridLayerTest.java

See https://issues.jboss.org/browse/GUVNOR-2754

GUVNOR-2754: Guided Decision Table Editor: Connectors re-appear when making changes in 'pinned' mode

---

uberfire-extensions/uberfire-security/uberfire-servlet-security/src/main/java/org/uberfire/ext/security/server/BasicAuthSecurityFilter.java
uberfire-extensions/uberfire-security/uberfire-servlet-security/src/test/java/org/uberfire/ext/security/server/BasicAuthSecurityFilterTest.java

see https://issues.jboss.org/browse/UF-442

UF-442: allow empty-password login

---

uberfire-commons/src/main/java/org/uberfire/commons/uuid/UUID.java
uberfire-commons/src/main/resources/org/uberfire/commons/UberfireCommons.gwt.xml
uberfire-commons/src/test/java/org/uberfire/commons/uuid/UUIDTest.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-api/src/main/java/org/uberfire/ext/wires/core/api/shapes/WiresBaseShape.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-client/src/main/java/org/uberfire/ext/wires/core/client/controlpoints/DefaultControlPoint.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-client/src/main/java/org/uberfire/ext/wires/core/client/magnets/DefaultMagnet.java

https://issues.jboss.org/browse/UF-445
Depends on this:
https://github.com/droolsjbpm/drools-wb/pull/354

UF-445 : Move UUID from uberfire-wires-core-api to uberfire-commons

---

uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/tree/TreeItem.java

See https://issues.jboss.org/browse/GUVNOR-2807
New methods to facilitate Unit Testing.

GUVNOR-2807: File Explorer in Admin view freezes when a project is extended

---

uberfire-workbench/uberfire-workbench-client-backend/src/test/java/org/uberfire/client/WorkbenchBackendEntryPointTest.java

@porcelli @manstis fixing tests from previous commit (which I broke by changing the log level). Same as on master...

Fix WorkbenchBackendEntryPointTest after log-level change

---

pom.xml
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/resources/org/uberfire/client/views/static/uberfire-variables.less

https://issues.jboss.org/browse/UF-461

UF-461: Upgrade PatternFly to 3.18

---

uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/LayoutEditorPluginImpl.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/LayoutEditorPresenter.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/api/LayoutEditor.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/container/Container.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/LayoutEditorPresenterTest.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/test/TestLayoutEditorPresenter.java

Merge with: https://github.com/droolsjbpm/kie-wb-common/pull/646

JBPM-5424: Version selector does not work in the new form modeler.

---

uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/common/StyleHelper.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/menu/MenuItemDivider.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/menu/MenuItemDividerView.html
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/menu/MenuItemDividerView.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/menu/MenuItemFactory.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/menu/MenuItemHeader.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/menu/MenuItemHeaderView.html
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/menu/MenuItemHeaderView.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/menu/MenuItemView.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/menu/MenuItemWithIcon.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/menu/MenuItemWithIconView.html
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/menu/MenuItemWithIconView.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/menu/MenuItemFactoryTest.java

See https://issues.jboss.org/browse/GUVNOR-2873

GUVNOR-2873: Guided Decision Table Editor: Change Edit, Insert and View menus to use MenuItems

---

uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IOServiceIndexedImpl.java
uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/IOServiceIndexedDotFileGitImplTest.java
uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/dotfiles/DotFileUtils.java
uberfire-nio2-backport/uberfire-nio2-model/src/test/java/org/uberfire/java/nio/base/dotfiles/DotFileUtilsTest.java

See https://issues.jboss.org/browse/RHBPMS-1889
The issue was that indexing was skipped when saving only meta-data (stored in "dot files").
This change ensures when only a "dot file" is changed the "real file" (and hence "dot file" too) is indexed.

RHBPMS-1889: Search by Find form does not work

---

uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/dotfiles/DotFileUtils.java
uberfire-nio2-backport/uberfire-nio2-model/src/test/java/org/uberfire/java/nio/base/dotfiles/DotFileUtilsTest.java

See https://issues.jboss.org/browse/RHBPMS-1889

[0.9.x] RHBPMS-1889: Search by Find form does not work

---

uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IOServiceIndexedImpl.java
uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/IOServiceIndexedDeleteFileTest.java

Fix failing tests on kie-wb-common and include test in uberfire.

RHBPMS-1889: Search by Find form does not work.

---

uberfire-showcase/uberfire-dynamic-plugin/pom.xml
uberfire-showcase/uberfire-dynamic-plugin/src/main/resources/assembly/assembly-webjar.xml

Dynamic Plugins now generates web jar files in maven build.
**Jar Structure:**
**File Size:**

Flat Web Jar Uberfire pom.xml Support

---

uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-wildfly/src/main/java/org/uberfire/ext/security/management/wildfly/properties/WildflyGroupPropertiesManager.java

Hey @ederign @csadilek @psiroky 
Took a look at the  race condition that sometimes is causing a concurrent a modification exceptio.  The issue I think is just due to the library implementation for that race condition and how I was using it.
If you look [here](https://gist.github.com/anonymous/fc3a5c6cdd7b05a08344c6036e32e9b9#file-propertiesfileloader-java-L172), it just says that you can have different threads accessing that resrouce, but it's not really an implemntation to serously consider for ensuring complete thread-safe support... Anyway, as far as I see they use to synchronize the PropertiesFileLoader instance itsel on the `getProperties()` method, so it was a bad idea to keep a reference for that properties in the uberfire wildfly groups manager and then iterating... because any …

Wildfly Security Management provider - Bug fixing

---

uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/NewProviderDefineDirTest.java

Continue to defaults to .niogit
Refactored test to check variation in the folder name

UF-491 - Allow changing git folder name via system property

---

uberfire-docs/docs/gettingStarted/5minIntroduction.md

Fixing the archetype version of the tutorial.

Fixing archetype version

---

uberfire-extensions/uberfire-security/uberfire-servlet-security/src/main/java/org/uberfire/ext/security/server/ServletSecurityAuthenticationService.java
uberfire-extensions/uberfire-security/uberfire-servlet-security/src/test/java/org/uberfire/ext/security/server/ServletSecurityAuthenticationServiceTest.java

@porcelli this is a forward port of https://github.com/uberfire/uberfire-extensions/pull/315

[RHBPMS-4574] hack to avoid logout issues with Keycloak

---

scripts/release/DSL-scripts/UBERFIRE_Release.sh
scripts/release/DSL-scripts/UF_pushTag.sh

DSL-scripts: removed uberfire-extensions from script

---

uberfire-extensions/uberfire-social-activities/uberfire-social-activities-backend/src/main/resources/META-INF/kmodule.xml

@psiroky Would you mind approving (fixes cause of Selenium test failures)

Remove old kmodule.xml declaration following move to guvnor.

---

uberfire-extensions/uberfire-social-activities/uberfire-social-activities-backend/src/main/resources/META-INF/kmodule.xml

(cherry picked from commit 0ae8bd6d88028b60cc42f7f957ef6a37ebe6d86f)
@psiroky FYI

[1.0.x] Remove old kmodule.xml declaration following move to guvnor.

---

uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/infra/UniqueIDGenerator.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/widgets/LayoutDragComponentGroupPresenter.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/widgets/LayoutDragComponentGroupView.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/infra/UniqueIDGeneratorTest.java

https://issues.jboss.org/browse/UF-496

[Layout editor] Expand/Collapse of Tools is not possible when more editors are open.

---

scripts/release/DSL-scripts/UF_deploy.sh

(cherry picked from commit 091151dd020c6af23f144c2b78c3e8f13d239081)

changes to appformer

---

pom.xml

Create project-sources archive during full build

---

uberfire-extensions/uberfire-apps/uberfire-apps-api/src/main/java/org/uberfire/ext/apps/api/DirectoryBreadcrumb.java
uberfire-extensions/uberfire-apps/uberfire-apps-api/src/test/java/org/uberfire/ext/apps/api/DirectoryBreadcrumbTest.java
uberfire-extensions/uberfire-apps/uberfire-apps-client/src/main/java/org/uberfire/ext/apps/client/home/AppsHomePresenter.java
uberfire-extensions/uberfire-apps/uberfire-apps-client/src/main/java/org/uberfire/ext/apps/client/home/AppsHomeView.java
uberfire-extensions/uberfire-apps/uberfire-apps-client/src/main/java/org/uberfire/ext/apps/client/home/AppsHomeView.ui.xml
uberfire-extensions/uberfire-apps/uberfire-apps-client/src/main/java/org/uberfire/ext/apps/client/resources/AppsCss.java
uberfire-extensions/uberfire-apps/uberfire-apps-client/src/main/resources/org/uberfire/ext/apps/client/resources/css/apps.css
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/breadcrumbs/UberfireBreadcrumbs.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/breadcrumbs/header/UberfireBreadcrumbsContainer.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/breadcrumbs/header/UberfireBreadcrumbsContainerImpl.css
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/breadcrumbs/header/UberfireBreadcrumbsContainerImpl.html
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/breadcrumbs/header/UberfireBreadcrumbsContainerImpl.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/breadcrumbs/UberfireBreadcrumbsTest.java

@paulovmr sorry for a new PR. I did a mistake on UF-462 and uf-462 :-(
https://github.com/AppFormer/uberfire/pull/682

Uberfire breadcrumbs adds extra space between navbar and perspective content

---

uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/menu/WorkbenchMenuBarPresenter.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/menu/WorkbenchMenuBarProducer.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/menu/WorkbenchMenuBarStandalonePresenter.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/widgets/menu/WorkbenchMenuBarProducerTest.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/widgets/menu/WorkbenchMenuBarStandalonePresenterTest.java

See https://issues.jboss.org/browse/RHBPMS-4707
This is the corollary of https://github.com/AppFormer/uberfire/pull/681 for master.
(cherry picked from commit ea4477afce4313294c1dc3c926322e4717f0c376) - RHBPMS-4706

RHBPMS-4707: Embedded Authoring perspective is broken when using parameter controlled URL

---

uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/ActivityBeansCache.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PerspectiveManagerImpl.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/mvp/ActivityBeansCacheTest.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/mvp/PerspectiveManagerTest.java

Cherry pick from: 
https://github.com/AppFormer/uberfire/commit/ea3f4b0de46fb8a5afac26ce8ea8396402b3df78

Upgraded Asset editor can broke navigation in Business Central

---

uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/breadcrumbs/UberfireBreadcrumbsView.css
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/breadcrumbs/header/UberfireBreadcrumbsContainerImpl.css
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/breadcrumbs/header/UberfireBreadcrumbsContainerImpl.java

https://github.com/kiegroup/kie-wb-distributions/pull/521

Breadcrumbs css fix for kie-distributions

---

uberfire-extensions/uberfire-social-activities/uberfire-social-activities-backend/src/main/java/org/ext/uberfire/social/activities/security/SocialSecurityConstraintsManager.java
uberfire-extensions/uberfire-social-activities/uberfire-social-activities-backend/src/test/java/org/ext/uberfire/social/activities/security/SocialSecurityConstraintsManagerTest.java

Last resort against evil SocialSecurityConstraint.

[GUVNOR-3059] Failing redeploy after deleting repo

---

uberfire-extensions/uberfire-apps/uberfire-apps-client/src/main/java/org/uberfire/ext/apps/client/home/components/popup/DirectoryNameValidator.java
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-backend/src/main/java/org/uberfire/ext/editor/commons/backend/validation/ValidationUtils.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/infra/NameValidator.java
uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/validation/NameValidator.java
uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java

Reverts AppFormer/uberfire#694

Revert "Avoid unnecessary repetitive calls to Pattern.compile()"

---

uberfire-extensions/uberfire-metadata/uberfire-metadata-api/src/main/java/org/uberfire/ext/metadata/model/KProperty.java
uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-lucene/src/main/java/org/uberfire/ext/metadata/backend/lucene/fields/FieldFactory.java
uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-lucene/src/main/java/org/uberfire/ext/metadata/backend/lucene/fields/SimpleFieldFactory.java
uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/KObjectUtil.java
uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/IOServiceIndexedSortingTest.java

See https://issues.jboss.org/browse/GUVNOR-3003

GUVNOR-3003: [Library] [Assets list] Order assets alphabetically

---

uberfire-extensions/uberfire-metadata/uberfire-metadata-api/src/main/java/org/uberfire/ext/metadata/model/KProperty.java
uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-lucene/src/main/java/org/uberfire/ext/metadata/backend/lucene/fields/FieldFactory.java
uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-lucene/src/main/java/org/uberfire/ext/metadata/backend/lucene/fields/SimpleFieldFactory.java
uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/KObjectUtil.java
uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/IOServiceIndexedSortingTest.java

See https://issues.jboss.org/browse/GUVNOR-3003
This is the corollary of https://github.com/AppFormer/uberfire/pull/697 for 1.0.x (branch name consistent with ```kiegroup``` PRs to allow Jenkins to build complete chain for other related PRs).
(cherry picked from commit a267be4fcf692189504f6dbbcf37c88bf3452ae3)

[1.0.x] GUVNOR-3003: [Library] [Assets list] Order assets alphabetically

---

uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/menu/WorkbenchMenuBarPresenter.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/menu/WorkbenchMenuBarProducer.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/menu/WorkbenchMenuBarStandalonePresenter.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/widgets/menu/WorkbenchMenuBarProducerTest.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/widgets/menu/WorkbenchMenuBarStandalonePresenterTest.java

See https://issues.jboss.org/browse/RHBPMS-4707
This is the corollary of https://github.com/AppFormer/uberfire/pull/684 for 1.0.x (7.0.0.Final)

[1.0.x] RHBPMS-4707: Embedded Authoring perspective is broken when using parameter controlled URL

---

pom.xml

This should be merged after 1.0.0.Final is released.

Upgrade Errai version to 4.0.1-SNAPSHOT

---

uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/tree/FSTreeItem.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/tree/Tree.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/tree/TreeItem.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/resources/org/uberfire/ext/widgets/core/client/resources/css/TreeNavigator.css
uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/test/java/org/uberfire/ext/widgets/core/client/tree/FSTreeItemTest.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/test/java/org/uberfire/ext/widgets/core/client/tree/TreeTest.java

This is an improvement of the uberfire tree used by stunner. [See this ticket](https://issues.jboss.org/browse/JBPM-5862).
Thanks

JBPM-5862: Stunner - Diagram tree explorer improvements.

---

uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/Select.java

Remove options using native jquery method instead.
Allow function to run deferred with refresh method.

JBPM-5990 - Fix inconsistent select state when update options

---

uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-backend/src/test/java/org/uberfire/ext/editor/commons/backend/service/CopyServiceImplTest.java

Removed class ResourceCopiedEventMock to use EventSourceMock instead.

Fix test event compilation error

---

uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/generator/PerspectiveEditorGenerator.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/dropdown/PerspectiveDropDown.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/dropdown/PerspectiveDropDownTest.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/authz/PerspectiveTreeProvider.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/ActivityBeansCache.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/authz/PerspectiveTreeProviderTest.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/mvp/ActivityBeansCacheTest.java

Fix + tests.
@ederign  Can you review & approve please?

DASHBUILDE-222: Custom persp. is offered in nav tree even after it's deleted

---

pom.xml
uberfire-showcase/uberfire-webapp/src/main/java/org/uberfire/client/ShowcaseEntryPoint.java
uberfire-showcase/uberfire-webapp/src/main/resources/org/uberfire/UberfireShowcase.gwt.xml
uberfire-workbench/uberfire-workbench-client-views-patternfly/pom.xml
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/sys/MomentUtils.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/sys/PatternFlyBootstrapper.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/sys/PatternFlyClientBundle.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/sys/MomentUtilsTest.java

Requirement for new date range picker widget
Matched available language locales with the ones used by kie-wb

JBPM-5990 - Add MomentJS library

---

uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/BaseEditor.java

See https://issues.jboss.org/browse/JBPM-6069

JBPM-6069: Missing CRUD buttons in asset editors

---

uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/rows/RowView.css
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/rows/RowView.html
uberfire-showcase/uberfire-webapp/src/main/java/org/uberfire/client/screens/widgets/WidgetsShowcasePresenter.java
uberfire-showcase/uberfire-webapp/src/main/java/org/uberfire/client/screens/widgets/WidgetsShowcaseView.html
uberfire-showcase/uberfire-webapp/src/main/java/org/uberfire/client/screens/widgets/WidgetsShowcaseView.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/JQueryProducer.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/Popover.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/widgets/PopoverTest.java

Fixing issues to load the data-* attributes properly.

JBPM-5990 - Improvements to Popover element

---

uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/bars/DocksCollapsedBar.java
uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/bars/DocksExpandedBar.java
uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/items/AbstractDockItem.java
uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/items/SideDockItem.java
uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/items/SideDockItemFocused.java
uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/items/SingleSideDockItem.java
uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/items/SouthDockItem.java
uberfire-extensions/uberfire-wires/uberfire-wires-webapp/pom.xml
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/listbar/ListBarWidgetImpl.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/listbar/PartListDropdown.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/listbar/ListBarWidgetImplTest.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/util/CSSLocatorsUtils.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/panels/impl/StaticWorkbenchPanelView.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/panel/ContextPanel.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/panel/StaticFocusedResizePanel.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/util/CSSLocatorsUtilsTest.java

@tomasdavidorg 
class for docks bars: qe-docks-bar-W (W is the side of the bar)
class for docks-items: qe-docks-item-W-org.kie.guvnor.explorer (W side, org.k Screen)
class for ListBar Header: qe-list-bar-header-CustomerSurvey-taskform.form---Others - format: qe-list-bar-header-file-type (I've replaced all " " to "-")
class for the content of the header:  qe-list-bar-content-CustomerSurvey-taskform.form---Others 
When there is no listbar, the main class is qe-static-workbench-panel-view

AF-518: Docks locators in Library asset view

---

uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/adapter/GroupAdapterAuthorizationSource.java
uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/security/JAASAuthenticationServiceTest.java

@romartin could you please take a look?

[0.9.x][RHBRMS-2839] return empty role/group list instead of null

---

uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/tree/FSTreeItem.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/tree/Tree.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/tree/TreeItem.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/test/java/org/uberfire/ext/widgets/core/client/tree/FSTreeItemTest.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/test/java/org/uberfire/ext/widgets/core/client/tree/TreeItemTest.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/test/java/org/uberfire/ext/widgets/core/client/tree/TreeTest.java

Refactored code to improve the performance of the uberfire tree and stunner tree explorer.
For more information see [this ticket](https://issues.jboss.org/browse/JBPM-5862).
This PR should be merged with [this kie-wb-common PR](https://github.com/kiegroup/kie-wb-common/pull/918) 
@romartin can you please review this PR?
Thanks.

JBPM-5862-2: Stunner - Diagram tree explorer improvements.

---

uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/LayoutEditorPluginImpl.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/LayoutEditorPresenter.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/api/LayoutEditor.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/widgets/LayoutDragComponentGroupPresenter.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/widgets/LayoutDragComponentGroupView.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/LayoutEditorPresenterTest.java

**To be merged before https://github.com/kiegroup/kie-wb-common/pull/887**
@pefernan could you give a look?

JBPM-5964 adding cancel button to field edition popup

---

uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/adapter/GroupAdapterAuthorizationSource.java
uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/security/JAASAuthenticationServiceTest.java

@krisv @markcoble fix for git clone issue
avoid using integrator that is cached as it's single run only.

RHBPMS-4796 - Git data transfer via SSH protocol fails on WAS server

---

uberfire-maven-utils/uberfire-maven-integration/src/main/java/org/appformer/maven/integration/ArtifactResolver.java
uberfire-maven-utils/uberfire-maven-integration/src/main/java/org/appformer/maven/integration/DependencyDescriptor.java
uberfire-maven-utils/uberfire-maven-integration/src/main/java/org/appformer/maven/integration/MavenPomModelGenerator.java
uberfire-maven-utils/uberfire-maven-integration/src/main/java/org/appformer/maven/integration/MavenRepository.java
uberfire-maven-utils/uberfire-maven-support/src/main/java/org/appformer/maven/support/AFReleaseId.java
uberfire-maven-utils/uberfire-maven-support/src/main/java/org/appformer/maven/support/AFReleaseIdImpl.java
uberfire-maven-utils/uberfire-maven-support/src/main/java/org/appformer/maven/support/DependencyFilter.java
uberfire-maven-utils/uberfire-maven-support/src/main/java/org/appformer/maven/support/MinimalPomParser.java
uberfire-maven-utils/uberfire-maven-support/src/main/java/org/appformer/maven/support/PomModel.java
uberfire-maven-utils/uberfire-maven-support/src/main/resources/org/appformer/maven/support/AFMavenSupportAPI.gwt.xml
uberfire-maven-utils/uberfire-maven-support/src/test/java/org/appformer/maven/support/PomModelParserTest.java

users (import wrong type).
Related:
https://github.com/kiegroup/droolsjbpm-knowledge/pull/243
https://github.com/kiegroup/drools/pull/1342

AF-558: rename ReleaseId in order to avoid problems with Drools/jBPM

---

uberfire-backend/uberfire-backend-cdi/src/main/java/org/uberfire/backend/server/cdi/workspace/WorkspaceScoped.java
uberfire-testing-utils/src/main/java/org/uberfire/mocks/MockInstanceImpl.java

related: https://github.com/kiegroup/guvnor/pull/469

[UF-516]: WorkspaceScoped repositories

---

uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/wizards/WizardViewImpl.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/test/java/org/uberfire/ext/widgets/core/client/wizards/WizardViewImplTest.java

See https://github.com/kiegroup/drools-wb/pull/541

GUVNOR-3070: Guided Decision Tables: Column Wizard - Edit mode

---

uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/api/ModalConfigurationContext.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/api/PanelConfigurationContext.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ColumnWithComponents.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ComponentColumn.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ComponentColumnView.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/container/Container.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/rows/Row.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/infra/ConfigurationContext.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/infra/DragHelperComponentColumn.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/components/container/ContainerTest.java

[UF-566] [Layout Editor] LayoutTemplate should be part of ConfigurationContext

---

uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/UberfireDocksImpl.java
uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/DocksBars.java
uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/test/java/org/uberfire/client/docks/UberfireDocksImplTest.java

JBPM-5542: Stunner - Properties Panel and Process Explorer are shown for incorrect asset
JBPM-6200: Docks aren't properly defined on stunner editor
Comment merge with: https://github.com/kiegroup/kie-wb-common/pull/973

JBPM-5542 & JBPM-6200 

---

uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/tables/ColumnPicker.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/tables/ColumnPickerTest.java

See https://issues.jboss.org/browse/GUVNOR-3351

GUVNOR-3351: Make validation dialog more readable

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseMoveHandler.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseMoveHandlerTest.java

See https://issues.jboss.org/browse/AF-582

AF-582: [Wires Grids] Panning canvas when in Pinned Mode should not move grid

---

uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/tables/ColumnPicker.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/tables/ColumnPickerTest.java

See https://issues.jboss.org/browse/GUVNOR-3351
This is the corollary of https://github.com/AppFormer/uberfire/pull/783 for 7.2.x
Branch name is ```-7.2.x``` so Jenkins can build related PRs successfully.
(cherry picked from commit c7b0f6279d981f67924f29907f20a16bbdf289c0)

[1.2.x] GUVNOR-3351: Make validation dialog more readable

---

uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/menu/megamenu/WorkbenchMegaMenuView.html
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/menu/megamenu/WorkbenchMegaMenuView.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/menu/megamenu/WorkbenchMegaMenuView.less
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/menu/megamenu/WorkbenchMegaMenuPresenter.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/menu/megamenu/WorkbenchMegaMenuProducer.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/menu/megamenu/WorkbenchMegaMenuStandalonePresenter.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/widgets/menu/megamenu/WorkbenchMegaMenuPresenterTest.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/widgets/menu/megamenu/WorkbenchMegaMenuProducerTest.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/widgets/menu/megamenu/WorkbenchMegaMenuStandalonePresenterTest.java

* Added compact collapse/expand button;
* Home link now considers the home set on security.

Mega Menu adjusts

---

pom.xml

[AF-600] upgrade freemarker to 2.3.26.jbossorg-1

---

uberfire-project-datamodel/uberfire-project-datamodel-api/src/main/java/org/appformer/project/datamodel/oracle/OperatorsOracle.java
uberfire-project-datamodel/uberfire-project-datamodel-api/src/test/java/org/appformer/project/datamodel/OperatorsOracleTest.java

https://issues.jboss.org/browse/GUVNOR-3479
This updates a list. Do we want to test the list content? 
Right now we don't do that.

GUVNOR-3479 : [GSS-RFE] Add support for missing keywords like "not matches" condition in Guided Rule

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/pinning/impl/RestrictedMousePanMediator.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/layer/pinning/impl/RestrictedMousePanMediatorTest.java

This is cherry-pick of #815 . @karreiro @manstis, please have a look when you have  moment.

[1.3.x] GUVNOR-3198: Increase RestrictedMousePanMediator coverage

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/GridLienzoPanel.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollBars.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollHandler.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollUI.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollable.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/GridLienzoPanelTest.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollBarsTest.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollHandlerTest.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollUITest.java

See https://issues.jboss.org/browse/GUVNOR-3468
---
- https://github.com/AppFormer/uberfire/pull/826
- https://github.com/kiegroup/kie-wb-common/pull/1158
- https://github.com/kiegroup/drools-wb/pull/611

GUVNOR-3468: GridLienzoPanel/GridLienzoScrollUI: Improve re-usability

---

uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/LayoutEditorView.css
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ColumnWithComponents.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/container/ContainerView.css
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/rows/Row.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/components/FullLayoutTest.java

Bugfix: drop inside a inner column also expanded drop area for empty layout (UX request)

---

uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/pom.xml
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/rows/Row.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/AbstractLayoutEditorTest.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/components/rows/RowTest.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/resources/org/uberfire/ext/layout/editor/client/columnWithComponentsLayout.txt

@jsoltes @ederign could you review?

[2.0.x] JBPM-6329: The group layout is created also on cancel.

---

uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/pom.xml
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/rows/Row.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/AbstractLayoutEditorTest.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/components/rows/RowTest.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/resources/org/uberfire/ext/layout/editor/client/columnWithComponentsLayout.txt

@jsoltes @ederign could you take a look

[1.3.x] JBPM-6329: The group layout is created also on cancel.

---

uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/common/InfoPopup.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/common/InfoPopupTest.java

@manstis 1.3.x was the Uberfire version used for drools-wb-7.3.x.

[1.3.x] GUVNOR-2825: [Guided Decision Table] Hints are empty

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dom/impl/BaseDOMElement.java

See https://issues.jboss.org/browse/GUVNOR-3487

GUVNOR-3487: Multi-select combo box in guided decision table only has a height of a single row

---

uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/WorkbenchLayout.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/WorkbenchLayoutImpl.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/panels/MaximizeToggleButtonPresenter.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/panels/impl/AbstractSimpleWorkbenchPanelView.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/panels/impl/MultiListWorkbenchPanelView.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/WorkbenchLayoutImplTest.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/panels/impl/AbstractDockingWorkbenchPanelViewTest.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/panels/impl/AbstractSimpleWorkbenchPanelViewTest.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/panels/impl/MultiListWorkbenchPanelViewTest.java

Cherry-picked from [master](https://github.com/AppFormer/uberfire/pull/836)

[7.3.x] JBPM-6210: Triple click on full screen button breaks layout

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dom/impl/BaseDOMElement.java

See https://issues.jboss.org/browse/GUVNOR-3487
This is the corollary of https://github.com/AppFormer/uberfire/pull/838 for 7.3.x
(cherry picked from commit a4dbeded2f2479e5ef716648a058a1d8a34abc3c)

[7.3.x] GUVNOR-3487: Multi-select combo box in guided decision table only has a height of a single row

---

uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/popups/DeletePopUpPresenter.java
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/popups/DeletePopUpView.html
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/popups/DeletePopUpView.java
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/popups/commons/ToggleCommentPresenter.java
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/file/popups/DeletePopUpPresenterTest.java

Replacement of #843 
@manstis @karreiro This is ensemble with kiegroup/drools-wb#629

GUVNOR-3511: Add possibility to change prompt and comment visibility

---

uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/popups/DeletePopUpPresenter.java
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/popups/DeletePopUpView.html
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/popups/DeletePopUpView.java
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/file/popups/commons/ToggleCommentPresenter.java
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/file/popups/DeletePopUpPresenterTest.java

This is cherry-pick of #844 , ensemble with kiegroup/drools-wb#631

[1.3.x] GUVNOR-3511: Add possibility to change prompt and comment visibility

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridData.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridDataTest.java

See https://issues.jboss.org/browse/GUVNOR-3344
Before:
After:

GUVNOR-3344: [Guided Decision Table] Editing BRL columns does not work

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridData.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/model/impl/BaseGridDataTest.java

Cherry-picked from https://github.com/AppFormer/uberfire/pull/845

[7.3.x] GUVNOR-3344: [Guided Decision Table] Editing BRL columns does not work

---

pom.xml

See https://issues.jboss.org/browse/GUVNOR-3394
Update to Lienzo version.
This is the corollary of https://github.com/AppFormer/uberfire/pull/849 for 1.3.x (7.3.x)
(cherry picked from commit 82bbfe804b941a24107932401a1a5d11d0724c47)

[7.3.x] GUVNOR-3394: [DMN Editor] Literal Expression: Line breaks for multiple line expressions

---

pom.xml
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-wildfly/pom.xml
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-wildfly/src/main/java/org/uberfire/ext/security/management/wildfly/properties/BaseWildflyPropertiesManager.java

@romartin could you please approve? These are the same changes as in #854, but for 7.3.x builds.

[1.3.x] [JBPM-6458] replace outdated jboss-sasl with wildfly-elytron

---

pom.xml
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-wildfly/pom.xml
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-wildfly/src/main/java/org/uberfire/ext/security/management/wildfly/properties/BaseWildflyPropertiesManager.java

@ederign or @romartin could you please take a look?

[JBPM-6458] replace outdated jboss-sasl with wildfly-elytron

---

uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ColumnWithComponents.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/rows/Row.java

@ederign could you review? (take a look at the email for all the details)

AF-587: Error when removing last field from a grouping.

---

uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/ACLSettingsTest.java
uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DefaultAuthorizationEntry.java
uberfire-security/uberfire-security-api/src/test/java/org/uberfire/security/impl/authz/DefaultPermissionManagerTest.java

See https://issues.jboss.org/browse/GUVNOR-3200
---
---
- https://github.com/AppFormer/uberfire/pull/861
- https://github.com/kiegroup/kie-wb-common/pull/1190
- https://github.com/kiegroup/drools-wb/pull/636
- https://github.com/kiegroup/kie-wb-distributions/pull/628
- https://github.com/kiegroup/kie-docs/pull/402

GUVNOR-3200: [Guided Decision Table] Access control to prohibit business users from modifying columns

---

uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/PerspectiveEditorPresenter.java
uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/PerspectiveEditorView.java
uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/layout/editor/PerspectiveEditorSettings.java
uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/test/java/org/uberfire/ext/plugin/client/perspective/editor/PerspectiveEditorPresenterTest.java
uberfire-extensions/uberfire-wires/uberfire-wires-webapp/src/main/java/org/uberfire/ext/wires/client/ShowcaseEntryPoint.java
uberfire-showcase/uberfire-webapp/src/main/java/org/uberfire/client/ShowcaseEntryPoint.java

The Tags button will remain hidden by default. Only the uberfire-webapp and uberfire-wires-webapp keep it visible.
@ederign Can you review/approve please?

AF-618: [Perspective Editor] Disable the "Tags" button

---

scripts/release/uberfire-pushTag.sh

(cherry picked from commit dd1e4bdd94b5829100e3c16db5dc57f68b2808b6)

the tags are pushed now to Gerrit instead of jboss-integration

---

scripts/release/uberfire-createAndDeploy.sh

kie-soup (master)  has to be released (now) before uberfire - please merge this

added sed change of kie-soup version

---

uberfire-extensions/uberfire-apps/uberfire-apps-backend/src/main/java/org/uberfire/ext/apps/impl/AppsPersistenceImpl.java
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/validation/Validator.java
uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/validation/ValidatorCallback.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-api/src/main/java/org/uberfire/ext/layout/editor/api/PerspectiveServices.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-backend/pom.xml
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-backend/src/main/java/org/uberfire/ext/layout/editor/impl/PerspectiveServicesImpl.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-backend/src/test/java/org/uberfire/ext/layout/editor/impl/PerspectiveServicesImplTest.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/LayoutEditorPluginImpl.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/api/LayoutEditorPlugin.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/container/Container.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/components/container/ContainerTest.java
uberfire-extensions/uberfire-preferences-ui-client/src/test/java/org/uberfire/ext/preferences/client/utils/PreferenceFormBeansInfoTest.java
uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-backend/src/main/java/org/uberfire/ext/plugin/backend/PluginServicesImpl.java
uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-backend/src/test/java/org/uberfire/ext/plugin/backend/PluginServicesImplTest.java
uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/editor/RuntimePluginBaseEditor.java
uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/PerspectiveEditorPresenter.java
uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/generator/PerspectiveEditorGenerator.java
uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/test/java/org/uberfire/ext/plugin/client/perspective/editor/layout/editor/ScreenLayoutDragComponentTest.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/ActivityBeansInfo.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/mvp/ActivityBeansInfoTest.java

Fixes related to the  copy and rename operations which fail under certain conditions. 
@ederign @tomasdavidorg  mind to take a look?

Fix copy/rename operations in the perspective editor

---

uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/dropdown/PerspectiveNameProvider.java
uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DotNamedPermission.java
uberfire-security/uberfire-security-api/src/test/java/org/uberfire/security/impl/authz/PermissionTest.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/authz/PerspectiveTreeProvider.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/authz/PerspectiveTreeProviderTest.java
uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/mvp/ActivityBeansCacheTest.java

Fix + tests.
@ederign Can you verify please?

AF-900: Pages are incorrectly named in the security settings UI

---

uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/editors/defaulteditor/DefaultEditorFileUploadBase.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/test/java/org/uberfire/ext/widgets/core/client/editors/defaulteditor/UploadEventTest.java

https://github.com/kiegroup/kie-wb-common/pull/1282

AF-822: Fix null in error message when uploading non-existing file

---

uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-api/src/main/java/org/uberfire/ext/layout/editor/api/PerspectiveServices.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-backend/src/main/java/org/uberfire/ext/layout/editor/impl/PerspectiveServicesImpl.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-backend/src/test/java/org/uberfire/ext/layout/editor/impl/PerspectiveServicesImplTest.java
uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/PerspectiveEditorPresenter.java
uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/generator/PerspectiveEditorActivity.java
uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/generator/PerspectiveEditorGenerator.java
uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/generator/PerspectiveEditorScreenActivity.java
uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/test/java/org/uberfire/ext/plugin/client/perspective/editor/generator/PerspectiveEditorGeneratorTest.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/PriorityDropDown.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/node/MultiplePermissionNodeEditor.java
uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/MultiplePermissionNodeEditorTest.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/dropdown/LiveSearchDropDown.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/dropdown/LiveSearchDropDownView.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/dropdown/LiveSearchEntry.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/dropdown/LiveSearchResults.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/dropdown/PerspectiveDropDown.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/dropdown/LiveSearchDropDownTest.java
uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/dropdown/PerspectiveDropDownTest.java

It fixes a couple of bugs reported by QE.
@kkufova @ederign mind to review please?

Layout editor fixes

---

uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/api/ComponentDropEvent.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/api/ComponentDropType.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/api/ComponentRemovedEvent.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ColumnWithComponents.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ComponentColumn.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/container/Container.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/rows/Row.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/rows/RowDrop.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/infra/ColumnDrop.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/AbstractLayoutEditorTest.java
uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/components/rows/RowTest.java

@ederign @jsoltes Could you please take a look?
This PR is a part of an ensemble, please merge with:
https://github.com/AppFormer/uberfire/pull/907
https://github.com/kiegroup/kie-wb-common/pull/1287

JBPM-6589: Field Settings lost after moving on layout

---

uberfire-workbench/uberfire-workbench-processors/src/main/java/org/uberfire/annotations/processors/GeneratorUtils.java

Added missing TypeMirrar and fixed some formats.
@mbarkley Can you review it please?

[AF-elemental2-type]: Adding elemental2 support. Fixing missing TypeMirror

---

uberfire-extensions/uberfire-social-activities/uberfire-social-activities-client/pom.xml
uberfire-extensions/uberfire-social-activities/uberfire-social-activities-client/src/main/java/org/ext/uberfire/social/activities/client/SocialEntryPoint.java
uberfire-extensions/uberfire-social-activities/uberfire-social-activities-client/src/test/java/org/ext/uberfire/social/activities/client/SocialEntryPointTest.java
uberfire-project/uberfire-project-api/src/main/java/org/guvnor/common/services/project/model/Project.java
uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/organizationalunit/OrganizationalUnit.java
uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/organizationalunit/OrganizationalUnitService.java
uberfire-structure/uberfire-structure-api/src/main/java/org/guvnor/structure/organizationalunit/impl/OrganizationalUnitImpl.java
uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitFactoryImpl.java
uberfire-structure/uberfire-structure-backend/src/main/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitServiceImpl.java
uberfire-structure/uberfire-structure-backend/src/test/java/org/guvnor/structure/backend/organizationalunit/OrganizationalUnitServiceTest.java
uberfire-structure/uberfire-structure-client/src/test/java/org/guvnor/structure/organizationalunit/OrganizationalUnitServiceCallerMock.java

AF-636: UX/UI improvements on spaces (teams) screen
AF-892: UX/UI improvements on projects screen

Library UX/UI improvements

---

uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/multipage/MultiPageEditorImpl.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/multipage/MultiPageEditorViewImpl.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/tab/TabPanelWithDropdowns.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/multipage/MultiPageEditorImplTest.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/multipage/MultiPageEditorViewImplTest.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/tab/TabPanelWithDropdownsCDITest.java
uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/tab/TabPanelWithDropdownsTest.java
uberfire-workbench/uberfire-workbench-client/pom.xml
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/multipage/MultiPageEditor.java
uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/multipage/MultiPageEditorView.java

See:
- https://issues.jboss.org/browse/RHBRMS-2946
- https://issues.jboss.org/browse/DROOLS-1828
---
---
- https://github.com/errai/errai/pull/303
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/617
- https://github.com/AppFormer/uberfire/pull/913
- https://github.com/kiegroup/drools-wb/pull/708

DROOLS-1828: [Guided Decision Table] New Toolbar

---

pom.xml
uberfire-bom/pom.xml
uberfire-showcase/uberfire-webapp/pom.xml

This reverts commit 7a5d58b59264cf29e689d0947ffe7e14fa8335b3.

upgraded jboss-ip-bom to 8.0.0.CR2

---

pom.xml

Upgrade Byteman to 3.0.10

---

uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseMoveHandler.java
uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseMoveHandlerTest.java

See https://issues.jboss.org/browse/DROOLS-2140

DROOLS-2140: [Guided Decision Table] Dragging table should be disabled when pinned
