AppFormer/uberfire

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/JGitUtil.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitUtilTest.java
Removed the Collections.sort that did not do the trick if the commits were committed at the same millisecond.
Added Collections.reverse since the list of VersionRecords is just in a reverse order.
>  UF-173 : VersionRecords that have the same timestamp are in the wrong order

- uberfire-io/src/test/java/org/uberfire/io/attribute/DotFileAttrViewTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/AbstractTestInfra.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProviderEncodingTest.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProviderTest.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/mvp/PlaceRequestHistoryMapperImplTest.java
* the tests were failing just when executed directly
using Maven (running from IDE was OK). However,
the clean-up should be done anyway.
* the Git tests are using random new port every
time. This makes them more robust in case there
is rogue process listeting on the default port
I think it makes sense to cherry-pick the fixes also into master and 0.6.x.
> Fix failing tests + make Git tests more robust

- uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/io/DisposableShutdownServiceTest.java
.when() was ambiguous (imported statically from
both Mockito and PowerMockito)
> Fix test compile error in jdt/eclipse

- pom.xml
* disabling the git/ssh daemons by default makes the tests more stable.
Maven build is usually executed in parallel (e.g. -TC), which means
tests in multiple modules are executed in parallel (in different JVM of course).
That sometimes leads into random test failures caused by failure
to bind to the default git/ssh ports.
Tested with both uberfire and uberfire-extensions repos (and with kie-wb running to make sure the ports are already bound).
> [UF-299] disable git/ssh daemons by default when running tests

- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/io/watch/AbstractIOWatchService.java
- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/io/watch/IOWatchServiceExecutorImpl.java
- uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/io/watch/AbstractIOWatchServiceTest.java
See https://bugzilla.redhat.com/show_bug.cgi?id=1323878
(cherry picked from commit f70ef4c059d312db1fc07692fb845fd703f3f82b - BZ1323572)
This is the corollary of https://github.com/uberfire/uberfire/pull/343 for 0.7.x.
> [0.7.x] BZ1323878: [GSS] (6.2.z) AsyncWatchService dies when a RuntimeException is thrown from IOWatchServiceExecutorImpl.execute()

- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/io/watch/AbstractIOWatchService.java
- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/io/watch/IOWatchServiceExecutorImpl.java
- uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/io/watch/AbstractIOWatchServiceTest.java
See https://bugzilla.redhat.com/show_bug.cgi?id=1323572
(cherry picked from commit f70ef4c059d312db1fc07692fb845fd703f3f82b)
> [0.8.x] BZ1323572: AsyncWatchService dies when a RuntimeException is thrown from IOWatchServiceExecutorImpl.execute()

- pom.xml
This fixes/workarounds the current issues with deploying SNAPSHOTs.
> Use canonical URLs for Maven deploy repositories

- scripts/release/update-version.sh
@mbiarnes could you please check this?
If you agree I think we should move most of the release logic into the scripts. The Jenkins should orchestrate the calling of the scripts (instead of having the logic in the job configs). The benefit of having the scripts in the git repo is that we can easily test them locally when doing changes.
> Add simple script for updating version during release

- uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/Properties.java
See https://bugzilla.redhat.com/show_bug.cgi?id=1333277
I've tested this with both XStream 1.4.7 (currently used on master); and XStream 1.4.9 (used by KIE master, 6.3.x and 6.4.x). See https://bugzilla.redhat.com/show_bug.cgi?id=1322171. I've asked @mbiarnes to consider upgrading Uberfire to 1.4.9 too for consistency.
> BZ1333277: Upgrade of XStream library to 1.4.9 causing exceptions during Project navigation

- uberfire-client-api/src/main/java/org/uberfire/client/annotations/WorkbenchEditor.java
- uberfire-client-api/src/main/java/org/uberfire/client/mvp/LockTarget.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/AbstractWorkbenchEditorActivity.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/LockManagerImpl.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/mvp/WorkbenchEditorActivityTest.java
- uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/WorkbenchEditorTest27.java
- uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/WorkbenchEditorTest8.java
- uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/expected/WorkbenchEditorTest27.expected
- uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/expected/WorkbenchEditorTest8.expected
See https://issues.jboss.org/browse/UF-306
```LockManager``` in ```AbstractWorkbenchEditorActivity``` is only instantiated *if* Uberfire is handling the locking; otherwise locking is left entirely to the editor itself. I also made a few changes to ```LockTarget``` (to support simplified Unit Testing) and related changes.
> UF-306: AbstractWorkbenchEditorActivity: Allow Editors to provide their own LockManager handling

- uberfire-client-api/src/main/java/org/uberfire/client/mvp/UpdatedLockStatusEvent.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/LockManagerImpl.java
See https://issues.jboss.org/browse/UF-308
This PR simply adds the ```Path``` associated with the ```UpdatedLockStatusEvent``` so I can disambiguate events relating to different locks.
> UF-308: UpdatedLockStatusEvent: Include Path parameter.

- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/mock/MockPlaceManager.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceManager.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceManagerImpl.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/panels/impl/PlaceManagerTest.java
See https://issues.jboss.org/browse/UF-311
This essentially makes an already public method on ```PlaceManagerImpl``` available on the interface ```PlaceManager``` refining it to filter by ```ResourceTypeDefinition```.
> UF-311: PlaceManager: Add the ability to retrieve a collection of PlaceRequests for an open Editor that can handle a ResourceTypeDefinition

- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-backend/src/main/java/org/uberfire/ext/editor/commons/backend/validation/ValidationUtils.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-backend/src/test/java/org/uberfire/ext/editor/commons/backend/validation/ValidationUtils_ParameterizedArtifactIdTest.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-backend/src/test/java/org/uberfire/ext/editor/commons/backend/validation/ValidationUtils_ParameterizedFilenameTest.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-backend/src/test/java/org/uberfire/ext/editor/commons/backend/validation/ValidationUtils_ParameterizedJavaIdTest.java
3 more PRs to follow (guvnor, kie-wb-common, jbpm-designer)
ValidationUtils class is copied and slightly extended (and then again copied) in other modules/repositories. This PR adds the extended functionality, so that the uberfire copy of the class can be re-used elsewhere (instead of being duplicated).
> Re-use uberfire's ValidationUtils

- uberfire-backend/uberfire-backend-cdi/src/main/java/org/uberfire/backend/server/cdi/SystemConfigProducer.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/resources/org/uberfire/ext/widgets/common/client/resources/css/common.css
Fixes warnings when starting OptaPlanner WB in Super Dev Mode
WARN  [org.jboss.weld.Event] WELD-000411: Observer method [BackedAnnotatedMethod] org.uberfire.backend.server.cdi.SystemConfigProducer.processAnnotatedType(@Observes ProcessAnnotatedType<Object>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
Computing all possible rebind results for 'org.uberfire.ext.widgets.common.client.resources.CommonResources'
Rebinding org.uberfire.ext.widgets.common.client.resources.CommonResources
[WARN] Line 208 column 25: encountered "=". Was expecting one of: "+" "-" "," "/" ")" <STRING> <IDENT> <NUMBER> <URL> <PERCENTAGE> <PT> <MM> <CM> <PC> <IN> <PX> <EMS> <EXS> <DEG> <RAD> <GRAD> <MS> <SECOND> <HZ> <KHZ> <DIMEN> <HASH> …
> UF-272 PLANNER-579: Reduce WARN messages during startup

- uberfire-client-api/src/main/java/org/uberfire/client/mvp/UberElement.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/LockManagerImpl.java
See https://issues.jboss.org/browse/GUVNOR-2507
This PR adds a ```UberView<P>``` equivalent for use with ```Element``` based Views and allows me to override a couple of bits in ```LockManagerImpl``` in a subclass I have in ```drools-wb``` (where I only want to fire the ```UpdatedLockStatusEvent``` if the lock has changed for the visible/active document - tied to opening multiple decision tables in the same editor).
> GUVNOR-2507: Guided Decision Table Editor: Add ability to open multiple decision tables in the same view

- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/common/DatePicker.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/common/DatePickerTest.java
@manstis @ederign  can you take a look? I have changed the code to avoid to use  the framework default language String. Only sets the datePicker to DatePickerLanguage.EN when the locale is "default" or it is not defined.
> RHBPMS-4014 Tasks fails on load for Chinese localization

- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/history/SaveButton.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/menu/BasicFileMenuBuilder.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/menu/BasicFileMenuBuilderImpl.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/menu/HasLockSyncMenuStateHelper.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/menu/BasicFileMenuBuilderTest.java
See https://issues.jboss.org/browse/GUVNOR-2548
This PR delegates the decision as to whether to enable or disable (or veto any change in state) to a helper class. The default implementation retains the current behaviour (I also have a new implementation in ```kie-wb-common``` - see linked PR - that only applies changes to ```MenuItem``` enabled state if change in lock is associated with the "active document".
> GUVNOR-2548: Guided Decision Table Editor: BasicFileMenuBuilderImpl: Support overriding default lock-sync behaviour

- pom.xml
- uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-parent-with-dependencies/pom.xml
[This issue](https://issues.jboss.org/browse/ERRAI-963) describes why errai-js is being removed. It seems as though it was only ever referenced in Uberfire in dependency management.
> ERRAI-963: Remove errai-js.

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetMouseClickHandler.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetMouseDoubleClickHandler.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/renderers/grids/impl/BaseGridRenderer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetMouseClickHandlerTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/impl/BaseGridWidgetMouseDoubleClickHandlerTest.java
Changed some mouse handlers to only try alternative checks if a match was not found by the prior check. There was a problem that selecting a "linked" column (which selects the "linked" grid) also was selecting the grid that contained the column clicked on - because a single "click" was handled twice; once to select the linked grid, and once to select the grid clicked on. Unit Test changes reflect the change in behaviour.
> GUVNOR-2559: Guided Decision Table Editor: Improve appearance (for Red Hat Summit) - Some colour changes and add icon to Linked columns

- uberfire-server/src/main/java/org/uberfire/server/cdi/UberFireGeneralFactory.java
- uberfire-server/src/test/java/org/uberfire/server/UberFireGeneralFactoryTest.java
This fixes issues described in [UF-335](https://jira.jboss.org/browse/UF-335).
> Return default user outside of HTTP session threads.

- pom.xml
- uberfire-parent-with-dependencies/pom.xml
This reverts commit 879b5c40d7b576af053463da132e741053267dd0.
As ip-bom 6.0.7.Final contains an upgrade to <version.com.thoughtworks.xstream>1.4.9 and this 
contains Java 8 (*non*-backwards compatibile) code, which causes Webpshere to prevent the BPMS
webservice from deploying we have to revert this.
> Revert "upgraded jboss-ip-bom to 6.0.7.Final (#402)"

- uberfire-server/src/main/java/org/uberfire/server/BaseFilteredServlet.java
This pull request is focused on resolving occurrence of Sonar rule
squid:S1166 - Exception handlers should preserve the original exception.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1166
Please let me know if you have any questions.
George Kankava
> squid:S1166 - Exception handlers should preserve the original exception

- uberfire-commons/src/main/java/org/uberfire/commons/regex/util/AntPathMatcher.java
This pull request is focused on resolving occurrences of Sonar rule
squid:S1168 - Empty arrays and collections should be returned instead of null.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1168
Please let me know if you have any questions.
George Kankava
> squid:S1168 - Empty arrays and collections should be returned instead of null

- src/main/config/zanata.xml
Created on Zanata a new project 1.0.0 (copied from the existing Zanata project 0.9.0).
Master branch should point to this new project.
The existing 0.9.0 project will be removed. New 0.9.0 Zanata projects (uberfire and uberfire-extensions) will be created based on Zanata projects 0.8.0.
The new uberfire and uberfire-extensions branches 0.9.x (will be branch tomorrow) will point to the new Zanata projects 0.9.0.
> added new Zanata 1.0.0 project

- uberfire-commons/src/main/java/org/uberfire/commons/regex/util/AntPathMatcher.java
- uberfire-io/src/main/java/org/uberfire/io/impl/cluster/helix/ClusterServiceHelix.java
- uberfire-io/src/main/java/org/uberfire/io/regex/AntPathMatcher.java
- uberfire-server/src/main/java/org/uberfire/server/FileUploadServlet.java
- uberfire-server/src/main/java/org/uberfire/server/util/FileServletUtil.java
This pull request is focused on resolving occurrences of Sonar rule
squid:S1192 - String literals should not be duplicated.
squid:S1132 - Strings literals should be placed on the left side when checking for equality.
squid:S3027 - String function use should be optimized for single characters.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1192
https://dev.eclipse.org/sonar/rules/show/squid:S1132
Please let me know if you have any questions.
George Kankava
> Multiple code improvements - squid:S1192, squid:S1132, squid:S3027

- uberfire-api/src/main/java/org/uberfire/workbench/model/CompassPosition.java
- uberfire-api/src/main/java/org/uberfire/workbench/model/NamedPosition.java
- uberfire-api/src/main/java/org/uberfire/workbench/model/Position.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/PanelManagerImpl.java
- uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/expected/PerspectiveTest12.expected
- uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/expected/PerspectiveTest13.expected
- uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/expected/PerspectiveTest16.expected
- uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/expected/PerspectiveTest17.expected
- uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/expected/PerspectiveTest18.expected
- uberfire-workbench/uberfire-workbench-processors-tests/src/test/resources/org/uberfire/annotations/processors/expected/PerspectiveTest19.expected
- uberfire-workbench/uberfire-workbench-processors/src/main/resources/org/uberfire/annotations/processors/templates/perspective.ftl
[This approach](https://github.com/uberfire/uberfire/blob/b3cc581826e5726cbfd350ab40fa53618b554d57/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/PanelManagerImpl.java#L447) for converting the `position` will fail when it's a `NamedPosition`.
This PR solves the `kie-wb-distributions` tests. :-)
> NamedPosition should be handled as a Position (instead of a CompassPosition)

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProviderBytemanTest.java
@ederign the test was commented because there is an unexpected behavior that locks the other test into that class. This is a workaround.
> Byteman test modified due an unexpected behaviour

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/ConcurrentJGitUtilTest.java
Concurrent JGitUtil access test.
Thread 1 : Keep committing new files to a repo
Thread 2 : Keep reading (resolvePath) an existing file in the repo.
It runs successfully in Linux (Fedora 22) but it constantly fails in Windows 7.
The loop counts (200 for committer thread. 2000 for reader thread) are arbitrary values that I can reproduce the issue constantly but try to minimize the test time. You may need to increase the values to reproduce the issue in a faster Windows machine.
> [RHBPMS-4105] concurrent JGit test

- pom.xml
See https://issues.jboss.org/browse/RHBRMS-2525
See also https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/267 for drools/jbpm.
This overrides the version in ip-bom until we move to a version containing jboss-integration/jboss-integration-platform-bom#327
> RHBRMS-2525: Business-central startup error: jGIT: Cannot run program 'bash'

- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/util/Layouts.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/util/LayoutsTest.java
@ederign @manstis  can you review/merge this please to fix the QE tests, see: https://issues.jboss.org/browse/GUVNOR-2654
Basically a panel definition could come from an external script, so I should've added this to begin with (see JavaDocs of PluginUtil). In this case (same script) it was just a mismatch of dealing with the default values (null, -1).
> GUVNOR-2654: Messages panel not visible

- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/menu/WorkbenchMenuBarPresenter.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/widgets/menu/WorkbenchMenuBarPresenterTest.java
See https://issues.jboss.org/browse/RHBRMS-349
The cause appears to be when a ```PerspectiveChange``` event is fired the ```WorkbenchMenuBarPresenter``` calls the Perspective's ```getMenus()``` method. These methods *could* set the ```MenuItems``` enabled/disabled state however when the menu is passed to the ```View``` the UI Elements' state is not synchronized with the ```MenuItem```. This fix forces the ```MenuItem``` state to be reflected in the UI Elements.
> RHBRMS-349: New Item Menu: No Project selected, all items enabled after Perspective reset

- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/menu/WorkbenchMenuBarPresenter.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/widgets/menu/WorkbenchMenuBarPresenterTest.java
See https://issues.jboss.org/browse/RHBRMS-349
(cherry picked from commit 0e0a2f809901629c0826798bcddfc4a5353898f2)
This is the corollary of https://github.com/uberfire/uberfire/pull/483 for 0.9.x
Note branch is called "RHBRMS-349-6.5.x" so Jenkins can compile with the related ```kie-wb-common``` PR.
> [0.9.x] RHBRMS-349: New Item Menu: No Project selected, all items enabled after Perspective reset (#483)

- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/history/VersionRecordManager.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/history/VersionRecordManagerTest.java
See https://issues.jboss.org/browse/GUVNOR-2680
@Rikkola could you please review. I may have fixed a symptom not the cause (as presumably ```VersionService``` may have used to always return at least one ```VersionRecord```). It could be the regression was introduced with the refactoring done for asset vs meta-data ```VersionRecords```.
If this "patch" is of a symptom and not the cause feel free to say!
> GUVNOR-2680: VersionRecordManager: Index Out of Bounds when opening a deleted file

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/util/ProxyAuthenticator.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProviderHttpProxyTest.java
> UF-407: Added support for proxy authentication using http[s].proxyUser

- uberfire-extensions/uberfire-metadata/uberfire-metadata-backends/uberfire-metadata-backend-lucene/src/main/java/org/uberfire/ext/metadata/backend/lucene/search/LuceneSearchIndex.java
See https://issues.jboss.org/browse/GUVNOR-2649
Terms do not seem to require escaping any more.. possibly changed when IP-BOM upgraded the version of Lucene (see https://github.com/jboss-integration/jboss-integration-platform-bom/commit/f5ac8e34052f5d640327515242f41dd2c4dd08ad)
> GUVNOR-2649: Asset search is broken

- uberfire-backend/uberfire-backend-server/pom.xml
- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/JAASAuthenticationService.java
- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/RoleLoader.java
- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/RoleRegistry.java
- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/WebAppListener.java
- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/WebAppSettings.java
- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/adapter/GroupAdapterAuthorizationSource.java
- uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/security/JAASAuthenticationServiceTest.java
- uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/security/RoleLoaderTest.java
- uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/security/WebAppSettingsTest.java
- uberfire-backend/uberfire-backend-server/src/test/resources/WEB-INF/web.xml
Fixed issue that causing the security principals not being added as roles in the current user instance, so remote login (eg: keycloak) were failing due to authorizations failed, as users had no roles. In order to do this I've backported from master branch the RoleRegistry necessary stuff.
See https://issues.jboss.org/browse/RHBPMS-4220
Please @dgutierr, as commented with you this fix, can you please verify? Thanks!
> RHBPMS-4220: Added RoleRegistry and registered principals that come from Keycloak remote logins as roles.

- pom.xml
Upgrade lienzo artifacts to latest versions as done in latest kie parent POM. See https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/commit/2cfb9acadaf0630045870625044c5170dff01ca2
@manstis Here it is! :)
> Upgrade lienzo core to 2.0.277 and lienzo tests to 1.0.0-RC3.

- uberfire-server/src/main/java/org/uberfire/server/FileUploadServlet.java
- uberfire-server/src/test/java/org/uberfire/server/FileUploadServletTest.java
Only on EAP 6.4 (running the version from the 6.5.x branch), [this solution](https://github.com/droolsjbpm/kie-docker-ci-images/pull/7) was not enough to solve this issue: https://issues.jboss.org/browse/RHBRMS-2519
So this workaround is needed:
```
request.setCharacterEncoding( "UTF-8" );
```
> [0.9.x] RHBRMS-2519: Upload File doesn't support multi-byte symbols in file name

- pom.xml
- uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-showcase/__rootArtifactId__-webapp/pom.xml
- uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/pom.xml
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-webapp/pom.xml
- uberfire-extensions/uberfire-wires/uberfire-wires-webapp/pom.xml
- uberfire-showcase/uberfire-webapp/pom.xml
- Also upgrade to guava 20.0-rc1, to replace
our custom fork
- Remove deletion of gwt unitCache to enable
persistent compilation unit cache in demos/showcases
> Upgrade to final GWT 2.8.0

- uberfire-extensions/uberfire-preferences/uberfire-preferences-client/src/main/java/org/uberfire/ext/preferences/client/admin/AdminPagePresenter.java
- uberfire-extensions/uberfire-preferences/uberfire-preferences-client/src/main/java/org/uberfire/ext/preferences/client/admin/AdminPageView.css
- uberfire-extensions/uberfire-preferences/uberfire-preferences-client/src/main/java/org/uberfire/ext/preferences/client/admin/AdminPageView.html
- uberfire-extensions/uberfire-preferences/uberfire-preferences-client/src/main/java/org/uberfire/ext/preferences/client/admin/AdminPageView.java
- uberfire-extensions/uberfire-preferences/uberfire-preferences-client/src/main/java/org/uberfire/ext/preferences/client/admin/page/AdminPageImpl.java
- uberfire-extensions/uberfire-preferences/uberfire-preferences-client/src/main/java/org/uberfire/ext/preferences/client/resources/i18n/Constants.java
- uberfire-extensions/uberfire-preferences/uberfire-preferences-client/src/main/resources/org/uberfire/ext/preferences/client/resources/i18n/Constants.properties
- uberfire-extensions/uberfire-preferences/uberfire-preferences-client/src/test/java/org/uberfire/ext/preferences/client/admin/AdminPagePresenterTest.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-webapp/pom.xml
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-webapp/src/main/java/org/uberfire/ext/security/management/client/ShowcaseEntryPoint.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-webapp/src/main/resources/org/uberfire/ext/security/management/UberfireSecurityManagementShowcase.gwt.xml
* Handled admin page wrong usage errors.
* Fixed admin page container height.
* Added counters for roles, groups and users on admin page on uberfire-security-management-webapp.
> UF-320: Adding counters for roles, groups and users on admin page

- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/FormLabelHelp.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/widgets/HelpIcon.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/widgets/FormLabelHelpTest.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/widgets/HelpIconTest.java
Make sure popover instance exists when setting help title/content.
> PLANNER-679: Workbench: Termination type tooltips are not displayed in the termination editor

- uberfire-server/src/main/java/org/uberfire/server/locale/GWTLocaleHeaderFilter.java
- uberfire-server/src/test/java/org/uberfire/server/locale/GWTLocaleHeaderFilterTest.java
- uberfire-server/src/test/resources/expected-2-sample.html
- uberfire-server/src/test/resources/expected-4-sample.html
See https://issues.jboss.org/browse/RHBPMS-4129
Use of ```response.getOutputStream().write( outputBytes )``` was double-encoding translated text.
I also updated to use ```org.apache.commons.lang3.LocaleUtils``` as Java's ```Locale``` constructor does not handle Language and Country locale formats (e.g. en_US).
> [0.9.x] RHBPMS-4129: Unlocalized 'Please wait. Loading application...' spinner.

- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/ChangePasswordView.ui.xml
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/AssignedEntitiesModalEditorView.ui.xml
Moves primary buttons to left to be the first button as in other modal dialogs and moves buttons from center to right in change password dialog.
> [UF-370]: update security modal dialogs layout

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/DefaultGridLayer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/DefaultGridLayerTest.java
See https://issues.jboss.org/browse/GUVNOR-2734
Cached "Connectors" were not being cleared when the Canvas was cleared.
> GUVNOR-2734: Guided Decision Table Editor: Close Analysis Report for graph editor

- uberfire-workbench/uberfire-workbench-processors/src/main/java/org/uberfire/annotations/processors/AbstractGenerator.java
The annotation processor sometimes failed when used
concurrently (e.g. in parallel Maven build). The reason
seems to be the fact that Freemarker's Configuration class
(or its dependencies) is not thread safe.
Synchronizing the Freemarker setup will likely make the init
sligthly slower, but since this is only build-time
(compile-time) processor it should not matter much.
@ederign, @manstis this seems to fix the issue we talked about today. I am running more build locally to make sure. However, I am not 100% sure about the implications of this change. WDYT? Is this OK?
> [UF-444] Avoid concurrent Freemarker setup

- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-backend/src/main/java/org/uberfire/ext/plugin/backend/MediaServletURIProducer.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-backend/src/main/java/org/uberfire/ext/plugin/backend/PluginMediaServlet.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-backend/src/test/java/org/uberfire/ext/plugin/backend/MediaServletURIProducerTest.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-backend/src/test/java/org/uberfire/ext/plugin/backend/PluginMediaServletTest.java
The `MediaServletURI` injection was not working because the method `produceMediaServletURI ` was not being used by WAS.
See https://issues.jboss.org/browse/RHBRMS-2687
> RHBRMS-2687: [Screen Plugin] Fail to upload picture on WAS and IE11

- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/plugin/GwtRuntimePluginWatcher.java
- uberfire-backend/uberfire-backend-server/src/test/java/org/uberfire/backend/server/plugin/GwtRuntimePluginWatcherTest.java
- An additional check makes sure the watcher is active
before processing plugin changes. This makes it much
less likely to happen but there's still a time window
in which it could occur
- Therefore if an error is thrown during shutdown
we just log it in debug level
> Avoid logging of plugin watcher errors during shutdown

- pom.xml
- uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-parent-with-dependencies/pom.xml
- uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-showcase/__rootArtifactId__-distribution-wars/pom.xml
- uberfire-archetype/uberfire-project-archetype/src/main/resources/archetype-resources/__rootArtifactId__-showcase/__rootArtifactId__-distribution-wars/src/main/assembly/assembly-showcase-tomcat-7_0.xml
- uberfire-bom/pom.xml
- uberfire-showcase/showcase-distribution-wars/pom.xml
- uberfire-showcase/showcase-distribution-wars/src/main/assembly/assembly-showcase-tomcat-7_0.xml
* CR5 brings JPA 2.1 + Hibernate 5.x
(upgraded from JPA 2.0 + Hibernate 4.x)
Please don't merge yet. All the IP BOM 7.0.0.CR5 PRs need to be merged together.
> Upgrade IP BOM to 7.0.0.CR5

- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-backend/src/main/java/org/uberfire/ext/editor/commons/backend/service/DeleteServiceImpl.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-backend/src/main/java/org/uberfire/ext/editor/commons/backend/service/helper/DeleteHelper.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-backend/src/test/java/org/uberfire/ext/editor/commons/backend/service/DeleteServiceImplTest.java
See https://issues.jboss.org/browse/GUVNOR-2820
This PR ensures ```DeleteHelper``` are invoked before the file(s) is deleted from VFS.
> GUVNOR-2820: Enumerations are present even if they were deleted

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProviderTest.java
Rename .gitignore to .gitkeep to describe the purpose of the file in a better way.
> UF-456: Rename .gitignore file created in empty directory to .gitkeep

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/GridLayerRedrawManager.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/GridLayerRedrawManagerTest.java
The comparator was initialized after the singleton instance was created,
causing a null comparator to be passed to the constructor of the commands
TreeSet and hence natural ordering to be used instead which didn't work
as Commands are not Comparable.
Since this type is a singleton it shouldn't have any other static fields
than instance to guarantee that the instance is in a proper state when
created.
This also caused ClassCastExceptions with generateJsInteropExports=true.
> Fix initialization ordering problem in GridLayerRedrawManager

- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ComponentColumnView.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/infra/DragHelperComponentColumn.java
> GWTBoostrap Widgets are not working in layout editor preview due to unattached gwt widgets

- uberfire-api/src/main/java/org/uberfire/mvp/impl/ConditionalPlaceRequest.java
- uberfire-api/src/main/java/org/uberfire/mvp/impl/DefaultPlaceRequest.java
- uberfire-api/src/main/java/org/uberfire/mvp/impl/PathPlaceRequest.java
- uberfire-api/src/main/java/org/uberfire/util/URIUtil.java
- uberfire-api/src/main/java/org/uberfire/workbench/model/PartDefinition.java
- uberfire-api/src/main/java/org/uberfire/workbench/model/impl/PartDefinitionImpl.java
- uberfire-api/src/main/resources/org/uberfire/jre/org/uberfire/util/URIUtil.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/breadcrumbs/UberfireBreadcrumbs.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/breadcrumbs/widget/BreadcrumbsPresenter.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/breadcrumbs/widget/BreadcrumbsView.css
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/breadcrumbs/widget/BreadcrumbsView.html
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/breadcrumbs/UberfireBreadcrumbsTest.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/pom.xml
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/listbar/ListBarWidgetImpl.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/listbar/ListBarWidgetImplTest.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/mock/MockPlaceManager.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceManager.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceManagerImpl.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PluginPlaceManagerImpl.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/panels/impl/PlaceManagerTest.java
* Breadcrumbs now can depend only on `Command`s;
* Breadcrumbs now can be cleared without clearing the toolbar;
* The cursor shown over breadcrumb items is now `pointer` (hand);
* A `MultiListWorkbenchPanelPresenter` can have unselectable parts, which means that the part can only be activated programmatically, it won't show in the header list and the header will be hidden. This improvement won't change the current default behavior;
* The `PlaceManager` now offers an option to close all places only if all of them can be closed. Otherwise, none will be;
* When going to a `PartDefinition`, the `PlaceManager` now checks if the part already is there, and select it. This behavior was only implemented when going to `PlaceRequest`s.
> Breadcrumbs, PlaceManager and ListBar improvements

- uberfire-backend/uberfire-backend-api/src/main/java/org/uberfire/backend/cdi/workspace/Workspace.java
- uberfire-backend/uberfire-backend-cdi/pom.xml
- uberfire-backend/uberfire-backend-cdi/src/main/java/org/uberfire/backend/server/cdi/model/WorkspaceImpl.java
- uberfire-backend/uberfire-backend-cdi/src/main/java/org/uberfire/backend/server/cdi/workspace/WorkspaceManager.java
- uberfire-backend/uberfire-backend-cdi/src/main/java/org/uberfire/backend/server/cdi/workspace/WorkspaceManagerPreferences.java
- uberfire-backend/uberfire-backend-cdi/src/main/java/org/uberfire/backend/server/cdi/workspace/WorkspaceScopeContext.java
- uberfire-backend/uberfire-backend-cdi/src/main/java/org/uberfire/backend/server/cdi/workspace/WorkspaceScoped.java
- uberfire-backend/uberfire-backend-cdi/src/main/java/org/uberfire/backend/server/cdi/workspace/WorkspaceScopedExtension.java
- uberfire-backend/uberfire-backend-cdi/src/main/resources/ErraiApp.properties
- uberfire-backend/uberfire-backend-cdi/src/main/resources/META-INF/beans.xml
- uberfire-backend/uberfire-backend-cdi/src/main/resources/META-INF/services/javax.enterprise.inject.spi.Extension
- uberfire-backend/uberfire-backend-cdi/src/test/java/org/uberfire/backend/server/cdi/SessionBasedBean.java
- uberfire-backend/uberfire-backend-cdi/src/test/java/org/uberfire/backend/server/cdi/WorkspaceBuilderService.java
- uberfire-backend/uberfire-backend-cdi/src/test/java/org/uberfire/backend/server/cdi/WorkspaceBuilderServiceTest.java
- uberfire-backend/uberfire-backend-cdi/src/test/java/org/uberfire/backend/server/cdi/workspace/WorkspaceManagerTest.java
- uberfire-backend/uberfire-backend-cdi/src/test/resources/ErraiApp.properties
- uberfire-backend/uberfire-backend-cdi/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider
- uberfire-backend/uberfire-backend-cdi/src/test/resources/logback.xml
_NOTE: I don't know if the files from the beginning should be there, so please let me know._
The Idea is to have a CDI Annotation to replace the @ApplicationScoped with it. This annotations lets a bean enter a Workspace context, so those beans have a single instance per workspace. Right now there is only one workspace per user, but that is going to change in the future.
> [UF-453]: WorkspaceScoped Beans added

- uberfire-api/src/main/java/org/uberfire/workbench/model/menu/EnabledStateChangeListener.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/menu/WorkbenchMenuBarPresenter.java
- Make sure EnableStateChangeListeners can be shared
across scripts including their enclosing scope
- Make sure menu items are iterable even if provided
by external script
> Fix support for menus in dynamic plugins

- uberfire-api/src/main/java/org/uberfire/workbench/model/menu/EnabledStateChangeListener.java
- This allows us to postpone activating jsinteropexports for all apps
while at the same time preventing the compiler optimization (inlining)
that caused problems for dynamic menus
> Refactor EnableStateChangeListener to a JsFunction

- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/common/StyleHelper.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/menu/MenuItemWithIconView.java
Refactor following move of ```HTMLElement``` helpers to ```errai-ui```.
See https://github.com/errai/errai/pull/232
> GUVNOR-2873: Guided Decision Table Editor: Change Edit, Insert and View menus to use MenuItems

- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IOServiceIndexedImpl.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IOServiceIndexedUtil.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/IOServiceIndexedDotFileGitInternalImplTest.java
Git internal "dot" files were being converted to a non-"dot" form which could then not be found on the underlying VFS. This fix skips indexing of git internal "dot" files.
> RHBPMS-1889: Search by Find form does not work.

- uberfire-extensions/uberfire-widgets/uberfire-widgets-table/pom.xml
- uberfire-extensions/uberfire-widgets/uberfire-widgets-table/src/main/java/org/uberfire/ext/widgets/table/client/UberfireSimpleTable.java
```UberfireSimpleTable``` uses jQuery to set CSS; however there is no guarantee jQuery has actually been loaded into the host page by whatever webapp is using this Widget.
> Ensure jquery is injected.

- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/common/BusyPopup.java
PR https://github.com/droolsjbpm/kie-wb-common/pull/711 has a failing test caused by the instantiation order of the ```BusyPopup``` "View" and ```BusyPopup``` "instance". The "View" needs to be instantiated before the popup "instance".
> Ensure UiBinder is instantiated before the instance of BusyPopup.

- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/container/ContainerView.html
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/container/ContainerView.java
The mobile preview on layout editor is not production ready. It's just a POC that gone too far.
Can we remove it? This will solve all those JIRA's.
https://issues.jboss.org/browse/UF-350
https://issues.jboss.org/browse/UF-499
https://issues.jboss.org/browse/UF-500
Another option is to implement that, but that will require some time to do this.
> Removing mobile preview poc

- pom.xml
Hey @manstis @psiroky 
This is the lienzo versions upgrade for uberfire too. See [this related PR](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/433).
Thanks!
> checkpoint.JBPM-5490: Upgrade to lienzo 2.0.287-RELEASE.

- pom.xml
Hey @manstis @psiroky
This is the lienzo upgrade for uberfire, while [the commit IP BOM](https://github.com/jboss-integration/jboss-integration-platform-bom/pull/366) is merged & the artifact released.
BTW - guys that's a pain! Three PRs (IP, KIE and UF BOMs) only for upgrading a single version... This is due our SNAPSHOT versions are using released IP BOMs, so we never have the latest versions and need to be overriding... isnt it?
Thanks!
> JBPM-5490: Upgrade to lienzo 2.0.287-RELEASE.

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/test/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProviderSSHTest.java
I believe the test only fails because of wrong setup. I tried to add `org.bouncycastle:bcprov-jdk15on:1.56` as a test dependency according to https://bugzilla.redhat.com/show_bug.cgi?id=1192072 but I wasn't successful so I suggest to ignore the test on IBM JDK until the proper setup is implemented. This will make QE life easier because we run the test on different JDKs and there are currently multiple failures related to platform-dependent tests.
Please cherry-pick to 1.0.x and master, too.
> UF-511: Ignore JGitFileSystemProviderSSHTest on IBM JDK

- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/ActivityBeansCache.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PerspectiveManagerImpl.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/mvp/ActivityBeansCacheTest.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/mvp/PerspectiveManagerTest.java
Could you please guys take a look? @hasys ? :)
This is an issue found by @hasys during QE of https://issues.jboss.org/browse/RHBPMS-4615.
Basically, what is going on is:
When a perspective is not transient, Uberfire stores its state on VFS and try to reload it.
The issue happens when I try to restore a state of a Place Request that doesn't exist anymore (Editors and Screens).
With this PR, if the state stored is invalid (null or references a Place Request that doesn't exist anymore) it's loads the default perspective definition.
When approved, this will be ported for 0.9.x and 1.0.x
> Upgraded Asset editor can broke navigation in Business Central

- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/menu/WorkbenchMenuBarPresenter.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/menu/WorkbenchMenuBarProducer.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/menu/WorkbenchMenuBarStandalonePresenter.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/widgets/menu/WorkbenchMenuBarProducerTest.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/widgets/menu/WorkbenchMenuBarStandalonePresenterTest.java
See https://issues.jboss.org/browse/RHBPMS-4706
This PR moves instantiation of the "Menu bar" to a helper to provide a different implementation for "default" vs "standalone" modes of operation (i.e. when workbench URL contains the ```standalone=true``` parameter). Tried and tested with (6.5.x) ```kie-wb``` and ```kie-drools-wb``` both "default" and "standalone" modes.. all OK.
> [0.9.x] RHBPMS-4706: [GSS](6.4.z) Embedded Authoring perspective is broken when using parameter controlled URL

- uberfire-extensions/uberfire-apps/uberfire-apps-client/src/main/java/org/uberfire/ext/apps/client/home/components/popup/DirectoryNameValidator.java
- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-backend/src/main/java/org/uberfire/ext/editor/commons/backend/validation/ValidationUtils.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/infra/NameValidator.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/validation/NameValidator.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
- uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
@porcelli please take a look and consider merging this.
Code using `<some string>.matches("regex")` internally calls `Pattern.compile(regex).matcher(input).matches()` The regex compilation step is much more expensive compared to matching step. Caching the Pattern (or avoiding regexes in some cases) will improve performance in these often-called cases.
> Avoid unnecessary repetitive calls to Pattern.compile()

- uberfire-workbench/uberfire-workbench-processors/src/main/java/org/uberfire/annotations/processors/AbstractGenerator.java
- uberfire-workbench/uberfire-workbench-processors/src/main/java/org/uberfire/annotations/processors/MultiTemplateLoader.java
Move FreeMarker ```Configuration``` to ```static``` to avoid multiple instance creation by concrete ```AbstractGenerator``` subclasses. Include a ```MultiTemplateLoader``` to accept incremental declaration of additional ```TemplateLoader``` for each successive annotation processor within Uberfire using the singleton ```Configuration``` instance.
FreeMarker's documentation states ```Configuration``` should be a singleton for the whole application and shared across threads (objects derived from ```Configuration``` are thread-safe). There remain sporadic compilation [failures](https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/kie-all-master/job/kie-all-build-master/721/console) caused by what appears to be multiple attempts to access configuration files from multiple invocation …
> Move FreeMarker Configuration to static

- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/main/java/org/uberfire/ext/metadata/io/IOServiceIndexedImpl.java
- uberfire-extensions/uberfire-metadata/uberfire-metadata-commons-io/src/test/java/org/uberfire/ext/metadata/io/BatchIndexConcurrencyTest.java
See https://issues.jboss.org/browse/UF-512
On investigation it appeared the ```WatchService``` was leading to the repository to be indexed in response to ```ioService().write(path1, "xxx!")``` before batch indexing's test threads had a chance to run. The test disables ```WatchService``` and just requests the ```FileSystem``` (which leads to batch indexing to execute). The test now also verifies there were 3 attempts to invoke indexing; and only one runs.
> UF-512: Index test randomly failing

- uberfire-nio2-backport/uberfire-nio2-model/src/main/java/org/uberfire/java/nio/base/AbstractPath.java
Sorry for the trouble this commit caused in https://github.com/AppFormer/uberfire/pull/694. I didn't realize that client-side doesn't support that. That being said I still think that this server-side change in AbstractPath is worth changing as I figure thousands of Path instances are created during normal operation of kie-wb. @porcelli WDYT?
> Avoid unnecessary Pattern.compile() in AbstractPath

- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/adapter/GroupAdapterAuthorizationSource.java
- uberfire-extensions/uberfire-security/uberfire-servlet-security/src/test/java/org/uberfire/ext/security/server/ServletSecurityAuthenticationServiceTest.java
In some cases (like one the described in the JIRA), the list of
principals contained a principal with 'null' name, which is
probably wrong. This caused a NPE further down as the name was used
to compute hashcode. Filtering the invalid principals seems to be
the easiest way to workaround that issue.
This is my very best guess as what is going on in the JIRA (given it does not contain a reproducer nor a list of steps to reproduce)
@porcelli or @romartin could you please take a look?
> [RHBPMS-4668] filter out invalid (null) login principals

- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/adapter/GroupAdapterAuthorizationSource.java
In some cases (like one the described in the JIRA), the list of
principals contained a principal with 'null' name, which is
probably wrong. This caused a NPE further down as the name was used
to compute hashcode. Filtering the invalid principals seems to be
the easiest way to workaround that issue.
Backport of #707.
> [0.9.x][RHBPMS-4669] filter out invalid (null) login principals

- uberfire-backend/uberfire-backend-server/src/main/java/org/uberfire/backend/server/security/adapter/GroupAdapterAuthorizationSource.java
- uberfire-extensions/uberfire-security/uberfire-servlet-security/src/test/java/org/uberfire/ext/security/server/ServletSecurityAuthenticationServiceTest.java
In some cases (like one the described in the JIRA), the list of
principals contained a principal with 'null' name, which is
probably wrong. This caused a NPE further down as the name was used
to compute hashcode. Filtering the invalid principals seems to be
the easiest way to workaround that issue.
Backport of #707
> [1.0.x][RHBPMS-4668] filter out invalid (null) login principals

- uberfire-api/src/main/java/org/uberfire/mvp/PlaceRequest.java
- uberfire-api/src/main/java/org/uberfire/mvp/impl/DefaultPlaceRequest.java
- uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/UberfireDocksImpl.java
- uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/main/java/org/uberfire/client/docks/view/DocksBars.java
- uberfire-extensions/uberfire-simple-docks/uberfire-simple-docks-client/src/test/java/org/uberfire/client/docks/view/DocksBarsTest.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/BookmarkableUrlHelper.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceHistoryHandler.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceManagerImpl.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/docks/UberfireDockPosition.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/docks/UberfireDocks.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/mvp/BookmarkableUrlHelperTest.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/mvp/PlaceHistoryHandlerTest.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/panels/impl/PlaceManagerTest.java
Bookmarkable URL - with this commit the URL reflects the status of the current perspective with its screens.
The URL is composed in the following way (special characters will be encoded of course):
* the perspective name is between the '#' and the '|' special characters;
* docks are contained in square brackets 
* screens not belonging to the current perspective are placed after a '$'
* non-docked closed screens are prepended with a '~'
* docked closed screens are prepended with a '!'
eg.:
http://127.0.0.1:8888/wires.html#WiresScratchPadPerspective|WiresScratchPadScreen,WiresLayersScreen,~WiresActionsScreen,WiresPaletteScreen,~WiresPropertiesScreen
http://127.0.0.1:8888/wires.html#UFWidgets|PagedTableScreen[WSimpleDockScreen,]
http://127.0.0.1:8888/kie-drools-wb.jsp#LibraryPerspective|$Pro …
> [UF-523]  Preserve Workbench State on the URL

- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/LayoutEditorView.css
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/api/LayoutDragComponent.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/api/RenderingContext.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ComponentColumnView.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/components/columns/ComponentColumnViewTest.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/layout/editor/ScreenLayoutDragComponent.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/layout/editor/popups/EditScreen.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/test/java/org/uberfire/ext/plugin/client/perspective/editor/layout/editor/ScreenLayoutDragComponentTest.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/test/java/org/uberfire/ext/plugin/client/perspective/editor/layout/editor/popups/EditScreenTest.java
Basically, two things addressed by this PR:
- Remove this hack: 
newProperties.put("random",		+        DefaultPlaceRequest place = new DefaultPlaceRequest(placeName,]     "" + (new Random().nextLong()));
The root cause for this is that I cannot close the screens when I remove them from the layout.
- Don't track the preview of screens on layout editor on the url:
DefaultPlaceRequest place = new DefaultPlaceRequest(placeName, properties, false)
> [Layout Editor + Bookmarkable URL] Don't track places on preview and proper cleanup of screen components

- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceHistoryHandler.java
Temporarily fix until https://issues.jboss.org/browse/AF-523 is ready.
Currently, back button is displaying an error popup. (before that it also doesn't work)
> [AF-541] [Bookmarkable URL] Back button is breaking Uberfire

- uberfire-extensions/uberfire-apps/uberfire-apps-client/src/main/java/org/uberfire/ext/apps/client/home/AppsHomeView.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/RuntimePluginsEntryPoint.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/config/PluginConfigService.java
- uberfire-extensions/uberfire-runtime-plugins/uberfire-runtime-plugins-client/src/main/java/org/uberfire/ext/plugin/client/perspective/editor/generator/PerspectiveEditorGenerator.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-client/src/main/java/org/uberfire/ext/security/management/client/ClientUserSystemManager.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/CommonsEntryPoint.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/breadcrumbs/UberfireBreadcrumbs.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-core/uberfire-widgets-core-client/src/main/java/org/uberfire/ext/widgets/core/client/CoreEntryPoint.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-table/src/main/java/org/uberfire/ext/widgets/table/client/TableEntryPoint.java
- uberfire-extensions/uberfire-wires/uberfire-wires-webapp/src/main/java/org/uberfire/ext/wires/client/ShowcaseEntryPoint.java
- uberfire-extensions/uberfire-wires/uberfire-wires-webapp/src/main/java/org/uberfire/ext/wires/client/navbar/AppNavBar.java
- uberfire-js/src/main/java/org/uberfire/client/JSEntryPoint.java
- uberfire-js/src/main/java/org/uberfire/client/exporter/UberfireJSAPIExporter.java
- uberfire-security/uberfire-security-client/src/main/java/org/uberfire/security/client/SecurityEntryPoint.java
- uberfire-showcase/uberfire-client-webapp/src/main/java/org/uberfire/client/navbar/AppNavBar.java
- uberfire-showcase/uberfire-webapp/src/main/java/org/uberfire/client/ShowcaseEntryPoint.java
- uberfire-showcase/uberfire-webapp/src/main/java/org/uberfire/client/navbar/AppNavBar.java
- uberfire-workbench/uberfire-workbench-client-backend/src/main/java/org/uberfire/client/WorkbenchBackendEntryPoint.java
- uberfire-workbench/uberfire-workbench-client-backend/src/test/java/org/uberfire/client/WorkbenchBackendEntryPointTest.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/HTML5DndSeleniumSupport.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/PatternFlyEntryPoint.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/ActivityBeansCache.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/Workbench.java
* Convert @AfterInitializations to @PostConstructs so that RPC
calls are queued before the bus initializes (and sent in a single payload)
* Minor refactoring in Workbench setup
* Workbench now adds itself as a blocker, unblocked once Errai is fully initialized
* Move HTML5DndSeleniumSupport to a module that includes JQuery (has an
implicit dependency that was not previously guaranteed to be on the host page)
> AF-546: Reduce startup time of AppFormer apps and workbenches

- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/BookmarkableUrlHelper.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceHistoryHandler.java
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/mvp/BookmarkableUrlHelperTest.java
Bookmarkable URL is now updated when an editor screen is closed, fixes AF-536 Cannot track closed editors.
This ticket belongs to (UF-195) Implement bookmarkable URLs
> AF-536: [Bookmarkable URL] Cannot track closed editors

- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/main/java/org/uberfire/ext/security/management/keycloak/client/auth/adapter/KCAdapterContextTokenManager.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-keycloak/src/test/java/org/uberfire/ext/security/management/keycloak/client/auth/adapter/KCAdapterContextTokenManagerTest.java
Fixed #JBPM-6278 NullPointerException when configuring user and group management services using KC adapter provider
> [JBPM-6278] NullPointerException when configuring user and group management services using KC adapter provider

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseMoveHandler.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/dnd/GridWidgetDnDMouseMoveHandlerTest.java
See https://issues.jboss.org/browse/AF-582
This is the corollary of https://github.com/AppFormer/uberfire/pull/792 for 1.2.x (7.2.x)
(cherry picked from commit e193e0c985c89a6c9336488d986bc82fd7cdab10)
> [1.2.x] AF-582: [Wires Grids] Panning canvas when in Pinned Mode should not move grid

- uberfire-io/pom.xml
- uberfire-nio2-backport/uberfire-nio2-model/pom.xml
The 'bundle' packaging is only needed when using the artifacts in OSGi
containers. None of the touched modules is being used in that way.
> Remove 'bundle' packaging where not needed

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/animation/GridWidgetEnterPinnedModeAnimation.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/animation/GridWidgetExitPinnedModeAnimation.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/DefaultGridLayer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/GridLienzoPanel.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/pinning/GridPinnedModeManager.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/pinning/impl/DefaultPinnedModeManager.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/pinning/impl/RestrictedMousePanMediator.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollBars.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollBounds.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollHandler.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollPosition.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollUI.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollable.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/animation/GridWidgetEnterPinnedModeAnimationTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/animation/GridWidgetExitPinnedModeAnimationTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/DefaultGridLayerTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/GridLienzoPanelTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/layer/pinning/impl/RestrictedMousePanMediatorTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollBarsTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollBoundsTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollHandlerTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollPositionTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollUITest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-webapp/src/main/java/org/uberfire/ext/wires/client/demo/grids/WiresGridsDemoViewImpl.java
See https://issues.jboss.org/browse/GUVNOR-3198
---
- https://github.com/AppFormer/uberfire/pull/808
- https://github.com/kiegroup/drools-wb/pull/583
- https://github.com/kiegroup/kie-wb-common/pull/1110
> GUVNOR-3198: [Guided Decision Table] Visual indication where the current view of Decision Table is located

- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/demo/WiresGridsDemoViewImpl.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/animation/GridWidgetEnterPinnedModeAnimation.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/grid/animation/GridWidgetExitPinnedModeAnimation.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/DefaultGridLayer.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/GridLienzoPanel.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/pinning/GridPinnedModeManager.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/pinning/impl/DefaultPinnedModeManager.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/layer/pinning/impl/RestrictedMousePanMediator.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollBars.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollBounds.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollHandler.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollPosition.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollUI.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/main/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollable.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/animation/GridWidgetEnterPinnedModeAnimationTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/animation/GridWidgetExitPinnedModeAnimationTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/DefaultGridLayerTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/layer/impl/GridLienzoPanelTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/layer/pinning/impl/RestrictedMousePanMediatorTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollBarsTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollBoundsTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollHandlerTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollPositionTest.java
- uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/scrollbars/GridLienzoScrollUITest.java
Cherry picked from https://github.com/AppFormer/uberfire/pull/808
---
- https://github.com/kiegroup/drools-wb/pull/594
- https://github.com/AppFormer/uberfire/pull/819
---
PS: We don't need to update `kie-wb-common` on `7.3.x`.
> [7.3.x] GUVNOR-3198: [Guided Decision Table] Visual indication where the current view of Decision Table is located

- uberfire-showcase/uberfire-webapp/pom.xml
No need to unpack the WildFly distribution when the GWT compilation is
skipped. It is not being used and only slows down the build (and takes
additional disk space)
> Skip WildFly dist unpacking when skipping GWT compilation

- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/tables/PagedTable.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/tables/PagedTableTest.java
reset currentPage to the first one when the page size is changed
> [1.3.x] JBPM-6238: NPE error thrown when switching the number of items per page

- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/common/InfoPopup.java
- uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/common/InfoPopupTest.java
See https://issues.jboss.org/browse/GUVNOR-2825
Setting title/content via super class constructor and calling recreate method.  The init() method of Popover class was never being called from InfoPopup so help messages were never displayed.
If the formatting is not liked don't blame me!  It is the latest Eclipse formatter.
> GUVNOR-2825: [Guided Decision Table] Hints are empty

- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/menu/UserMenu.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/menu/UserMenuViewImpl.java
- uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/menu/UserMenuTest.java
Cherry-picked from [master](https://github.com/AppFormer/uberfire/pull/840)
> [7.3.x] AF-615: Items in the logout menu duplicated every time navigation tree is changed

- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/test/java/org/uberfire/ext/security/management/client/widgets/management/editor/acl/ACLSettingsTest.java
- uberfire-security/uberfire-security-api/src/main/java/org/uberfire/security/impl/authz/DefaultAuthorizationEntry.java
- uberfire-security/uberfire-security-api/src/test/java/org/uberfire/security/impl/authz/DefaultPermissionManagerTest.java
See https://issues.jboss.org/browse/GUVNOR-3200
---
Cherry-picked from https://github.com/AppFormer/uberfire/pull/861
---
- https://github.com/AppFormer/uberfire/pull/863
- https://github.com/kiegroup/kie-docs/pull/407
- https://github.com/kiegroup/kie-wb-distributions/pull/634
- https://github.com/kiegroup/drools-wb/pull/644
- https://github.com/kiegroup/kie-wb-common/pull/1222
> [7.3.x] GUVNOR-3200: [Guided Decision Table] Access control to prohibit business users from modifying columns

- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/authz/EditorTreeProvider.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/resources/i18n/PermissionTreeI18NImpl.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/resources/i18n/PermissionTreeI18n.java
- uberfire-workbench/uberfire-workbench-client/src/main/resources/org/uberfire/client/resources/i18n/PermissionTreeConstants.properties
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/authz/EditorTreeProviderTest.java
See https://issues.jboss.org/browse/GUVNOR-3524
This PR adds ```PermissionTreeProvider``` for "registered editors" (i.e. a white-list of editors we want to control access to).
> GUVNOR-3524: Do not expose unsupported features by UI (e.g. scorecards, decision trees)

- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/authz/EditorTreeProvider.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/resources/i18n/PermissionTreeI18NImpl.java
- uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/resources/i18n/PermissionTreeI18n.java
- uberfire-workbench/uberfire-workbench-client/src/main/resources/org/uberfire/client/resources/i18n/PermissionTreeConstants.properties
- uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/authz/EditorTreeProviderTest.java
See https://issues.jboss.org/browse/GUVNOR-3524
This is the corollary of https://github.com/AppFormer/uberfire/pull/859 for 7.3.x
(cherry picked from commit 9de3efa4ef839cec95d7c8f3a72a844d8c6b83ff)
> [7.3.x] GUVNOR-3524: Do not expose unsupported features by UI (e.g. scorecards, decision trees)

- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/LayoutEditorView.css
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/columns/ColumnWithComponents.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/container/ContainerView.css
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/components/rows/Row.java
- uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/components/FullLayoutTest.java
Copy of https://github.com/AppFormer/uberfire/pull/862
This also includes a fix that's present on master but not on 1.4.x branch. Without that fix my changes doesn't work.
@ederign could you review?
> [1.4.x] AF-587: Error when removing last field from a grouping

- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-client-wb/src/main/java/org/uberfire/ext/security/management/client/screens/editor/GroupEditorScreen.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-client-wb/src/main/java/org/uberfire/ext/security/management/client/screens/editor/RoleEditorScreen.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-client-wb/src/main/java/org/uberfire/ext/security/management/client/screens/editor/UserEditorScreen.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-client-wb/src/test/java/org/uberfire/ext/security/management/client/screens/editor/GroupEditorScreenTest.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-client-wb/src/test/java/org/uberfire/ext/security/management/client/screens/editor/RoleEditorScreenTest.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-security-management-client-wb/src/test/java/org/uberfire/ext/security/management/client/screens/editor/UserEditorScreenTest.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/group/workflow/GroupEditorWorkflow.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/role/workflow/BaseRoleEditorWorkflow.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/user/workflow/BaseUserEditorWorkflow.java
- uberfire-extensions/uberfire-security/uberfire-security-management/uberfire-widgets-security-management/src/main/java/org/uberfire/ext/security/management/client/widgets/management/editor/user/workflow/UserCreationWorkflow.java
Hey @manstis @tomasdavidorg 
Promised this is the last one urgent for the LA release... can you please take a look at it? :) I'll do the cherry-pick once merged.
[See here](https://issues.jboss.org/browse/AF-477) the JIRA ticket for this bug.
Notice I did not found any other way rather than using the `confirm` method from the `Window` jsinterop API to  implement the screens' `@OnMayClose`, as the popup that the users management ui uses (from uberfire) seems to be a modal and is not possible to return the right value. So finally just did as the workbench Editors' do, show a native confirm box.
It **depends on** https://github.com/errai/errai/pull/292
Thanks!
> AF-477: [Security management] Security setting changes are lost if perspective is changed

- uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/main/java/org/uberfire/ext/editor/commons/client/htmleditor/HtmlEditorView.html
@jsoltes @ederign this PR fixes a typo... sorry.
> [2.0.x] AF-434: [HTML editor] Font size, Font color and Backgroud color are not working. (fixes typo)

- uberfire-io/pom.xml
- uberfire-io/src/main/java/org/uberfire/io/impl/cluster/helix/ClusterServiceHelix.java
- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/JGitFileSystemProvider.java
Now the clusterService injection to JGitFileSystemProvider is simplified
(in the end we never managed to isolate cluster per repository anyway).
> AF-634: fix for SSH issue not propagating to the rest of the cluster.

- uberfire-m2repo-editor/uberfire-m2repo-editor-api/pom.xml
- uberfire-m2repo-editor/uberfire-m2repo-editor-backend/pom.xml
- uberfire-project/uberfire-project-backend/pom.xml
- uberfire-rest/uberfire-rest-backend/pom.xml
- uberfire-structure/uberfire-structure-backend/pom.xml
Fixing: 
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.uberfire:uberfire-m2repo-editor-api:jar:2.0.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.jboss.errai:errai-common:jar -> duplicate declaration of version (?) @ org.uberfire:uberfire-m2repo-editor-api:[unknown-version], /Users/ederign/projects/forks/uberfire/uberfire-m2repo-editor/uberfire-m2repo-editor-api/pom.xml, line 61, column 17
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.uberfire:uberfire-m2repo-editor-backend:jar:2.0.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: …
> Pom cleanup

- uberfire-m2repo-editor/uberfire-m2repo-editor-client/src/main/java/org/guvnor/m2repo/client/upload/UploadFormPresenter.java
- uberfire-m2repo-editor/uberfire-m2repo-editor-client/src/main/java/org/guvnor/m2repo/client/upload/UploadFormView.java
- uberfire-m2repo-editor/uberfire-m2repo-editor-client/src/main/java/org/guvnor/m2repo/client/upload/UploadFormViewImpl.java
- uberfire-m2repo-editor/uberfire-m2repo-editor-client/src/test/java/org/guvnor/m2repo/client/upload/UploadFormTest.java
Method handleSubmit(SubmitEvent event) was never called due to a bug in gwt-bootstrap3, see https://github.com/gwtbootstrap3/gwtbootstrap3/issues/375. The fix is a workaround that enables the validation of the file name before submitting the form. 
@karreiro Could you, please, take a look at this fix?
> AF-650: Upload without choosing file causes exception in Artifact repository

- uberfire-api/src/main/java/org/uberfire/workbench/model/menu/MenuFactory.java
- uberfire-api/src/main/java/org/uberfire/workbench/model/menu/impl/MenuBuilderImpl.java
- uberfire-api/src/test/java/org/uberfire/workbench/model/menu/MenuFactoryTest.java
- uberfire-api/src/test/java/org/uberfire/workbench/model/menu/impl/MenuBuilderImplTest.java
See https://issues.jboss.org/browse/RHBRMS-3022
Before:
After:
---
Menus from other editors were interfering with permissions to enable/disable delete (and other buttons) in the Project Editor.
---
- https://github.com/AppFormer/uberfire/pull/903
- https://github.com/kiegroup/kie-wb-common/pull/1284
> RHBRMS-3022: Cannot disable "Delete" button for Analyst role in business central

- uberfire-nio2-backport/uberfire-nio2-impls/uberfire-nio2-jgit/src/main/java/org/uberfire/java/nio/fs/jgit/ws/JGitWatchEvent.java
@ederign please check. This System.out.println causes bunch of useless logs being printed in appserver console every time user does something with project assets. 
<details> <summary>like this</summary>
<pre>
7:17:26,516 INFO  [stdout] (default task-126) default://master@preferences/config/user/testadmin/LibraryInternalPreferences.preferences
07:22:54,736 INFO  [stdout] (default task-29) default://master@myrepo/abc/.global
07:22:54,736 INFO  [stdout] (default task-29) default://master@myrepo/abc/global/.gitkeep
07:22:54,737 INFO  [stdout] (default task-29) default://master@myrepo/abc/global/customeditors.json
07:22:54,737 INFO  [stdout] (default task-29) default://master@myrepo/abc/global/defaultemailicon.gif
07:22:54,737 INFO  [stdout] (default task-29) …
> Remove useless System.out.println
